### ISSUE TITLE
Organize the plug-ins in a store-only folder for third-party plugins

### ISSUE THREAD

**Issue by crashzk** [nuclearsilo583/zephyrus-store-preview-new-syntax#1]
Currently all plugins in the store and others made for it are all inside the **`plugins`** folder:
![image](https://user-images.githubusercontent.com/32937653/111254317-89c70200-85f3-11eb-8f37-7a40dbcb03c5.png)

It would be interesting to leave only the main plugin in the plugins folder and the others inside the plugins folder to create the **`store`** folder and the plugins store modules inside it, as VIP Core & Levels Ranks currently does, I believe it is more organized.

**Comment by nuclearsilo583** [comment]
Current build is able to place store.smx to plugins folder and other any module can place any where except the disabled folder. I used store.smx in plugins/ and other in plugins/shop_zephyrus/ without any error. Try
![Untitled](https://user-images.githubusercontent.com/58926275/111265978-7a2fd380-865c-11eb-8154-722ea2b0d775.png)
 it

**Comment by crashzk** [comment]
It really works, thanks for the information.
