### ISSUE TITLE
Database?

### ISSUE THREAD

**Issue by ardahzr** [nuclearsilo583/zephyrus-store-preview-new-syntax#10]
I guess that's what happened after doing the reset database for store from the admin menu. I compiled the plugins again. I tried to install but it didn't work. How can I fix 

`store-trade.smx (Store - Trade System): Native not found: Store_RegisterMenuHandler
store.smx (Store - The Resurrection with preview rewritten compilable with SM 1.10 new syntax): Error detected in plugin startup (see error logs)
store_custom_model.smx (Store Custom Weapon Models): Native "Store_RegisterHandler" was not found
store_gamble_coinflip.smx (Store - Coinflip gamble module): Native "Store_GetClientCredits" was not found
store_gamble_crowns.smx (Store - Crowns gamble module): Native "Store_GetClientCredits" was not found
store_gamble_dice.smx (Store - Dice gamble module): Native "Store_GetClientCredits" was not found
store_gamble_jackpot.smx (Store - Jackpot gamble module): Native "Store_GetClientCredits" was not found
store_gamble_roulette.smx (Store - Roulette gamble module): Native "Store_GetClientCredits" was not found
store_gamble_teambet.smx (Store - Teambet gamble module): Native "Store_GetClientCredits" was not found
store_item_admin.smx (Store - Admin / Vip Flags Fore Store): Native "Store_RegisterHandler" was not found
store_item_bulletsparks.smx (Store - Bulletsparks item module): Native "Store_RegisterHandler" was not found
store_item_bullet_impact.smx (Store - Bullet impact item module): Native "Store_RegisterHandler" was not found
store_item_cpsupport.smx (Store - Chat Processor item module): Native "Store_RegisterHandler" was not found
store_item_hats.smx (Store - Hats Module): Native "Store_RegisterHandler" was not found
store_item_hats_no_thirdpersion.smx: Native "Store_RegisterHandler" was not found
store_item_info.smx (Store - Info panel item module): Native "Store_RegisterHandler" was not found
store_item_link.smx (Store - Link item module): Native "Store_RegisterHandler" was not found
store_item_mvpsound.smx (Store - MVP sound item module): Native "Store_RegisterHandler" was not found
store_item_particle.smx (Store - Particle item module): Native "Store_RegisterHandler" was not found
store_item_pet.smx (Store - Pet item module): Native "Store_RegisterHandler" was not found
store_item_playerskins_no_zr_version.smx (Store - Player Skin Module (No ZR version)): Native "Store_RegisterHandler" was not found
store_item_tracers.smx (Store - Tracers Module): Native "Store_RegisterHandler" was not found
store_item_trails.smx (Store - Tracers Module): Native "Store_RegisterHandler" was not found
store_misc_lootbox.smx (Store - Lootbox module): Native "Store_RegisterHandler" was not found`

**Comment by nuclearsilo583** [comment]
Try to restart the server, check if you have gamedata in the server. 
Every action related to store core (edit items.txt, reset database, edit a row or information in database sheet) requires a server restart
