### ISSUE TITLE
Custom weapon models stickers bug

### ISSUE THREAD

**Issue by exd02** [nuclearsilo583/zephyrus-store-preview-new-syntax#100]
I have an AK with 4 equiped stickers:
![download](https://user-images.githubusercontent.com/62575526/184692181-74cc8997-0adf-4b60-9ce0-b488fae54bc1.png)
In store.txt:
```
"AK47 Girl94"
{
	"model"	"models/weapons/v_girl94.mdl"
	"worldmodel"	"models/weapons/w_girl94.mdl"
	"dropmodel"	"models/weapons/w_girl94_dropped.mdl"
	"entity"	"weapon_ak47"
	"type"	"CustomModel"
	"unique_id"	"uid_weapon_ak47girll94"
	"preview"	"1"
	"slot"	"1"
	"price"	"7500"
}
```
When I use the ak47 weapon model my stickers are bugged in the middle of the screen
![download](https://user-images.githubusercontent.com/62575526/184692643-98132725-9f1f-4911-a2dd-6f1cdd290b30.png)

Can you do a loop to remove the stickers from the weaponmodels?
Thank you!

**Comment by nuclearsilo583** [comment]
some custom model doesnt have the 4 required attachments point for sticker on the model, so this will happen and there're no way we can remove the sticker from client weapon exept force the vanilla weapon here https://forums.alliedmods.net/showthread.php?t=319179.

**Comment by exd02** [comment]
Thanks!

**Comment by nuclearsilo583** [comment]
Please note that post will force ALL weapon to vanilla weapon and will mess up your loadout.
Ex: you will have p2000 instead of usp.
You can reopen this if you have any problem.
