### ISSUE TITLE
Issue player models

### ISSUE THREAD

**Issue by Lund1337** [nuclearsilo583/zephyrus-store-preview-new-syntax#104]
After selecting player model, i get this error.

L 08/26/2022 - 15:21:32: [SM] Exception reported: Array index out-of-bounds (index -2, limit 768)
L 08/26/2022 - 15:21:32: [SM] Blaming: store.smx
L 08/26/2022 - 15:21:32: [SM] Call stack trace:
L 08/26/2022 - 15:21:32: [SM]   [1] Line 4290, store.sp::Store_UseItem
L 08/26/2022 - 15:21:32: [SM]   [2] Line 2946, store.sp::MenuHandler_Item

items.txt>

	"Models"
	{
		"Carnage"
		{
			"model" "models/player/custom_player/night_fighter/fortnite/carnage/carnage.mdl"
			"arms" "models/player/custom_player/night_fighter/fortnite/carnage/carnage_arms.mdl"
			"type" "playerskin"
			"unique_id"			"uid_model_carnage"
			"price" "10000"
		}
	}
	
store.cfg>
sm_store_playerskin_delay "3.5"
sm_store_playerskin_force_default "0"
sm_store_playerskin_instant "0"
sm_store_playerskin_enable "1"

plugin store_item_playerskins load>
] sm_rcon sm plugins load store_item_playerskins
No Zombie:Reloaded plugin detected
Gloves plugin detected
[SM] Loaded plugin store_item_playerskins.smx successfully.

I have ArmsFix.ext.2.csgo.so exentension and n_arms_fix.smx plugin running.
You could also contact me on discord, Lund#4846.

**Comment by nuclearsilo583** [comment]
What version of the store.smx you're using. Btw you can't unload/load the plugin via sm command. All the stuff related to the store need a full server restart.

**Comment by Lund1337** [comment]
I was only testing to see if the plugin detected my gloves plugin, at first i forgot to rename it to 'gloves'
] sm_rcon sm plugins info store
  Filename: store.smx
  Title: Store - The Resurrection with preview rewritten compilable with SM 1.10 new syntax (A completely new Store system with preview rewritten by nuclear silo)
  Author: Zephyrus, nuclear silo, AiDN™
  Version: 7.0.4
  Status: running
  Timestamp: 08/26/2022 21:56:56
  Hash: 6146262c274ebe963e283d2df5884fba
  Also tested version 7.0.6 , same issue.

**Comment by nuclearsilo583** [comment]
Give me your sm plugins lists and your items.txt via pastebin.com

**Comment by Lund1337** [comment]
Plugins list>
https://pastebin.com/dxAhtC9x
Pastebin wouldn't let me post items.txt content for whatever reason, items.txt contect here>
https://controlc.com/df270799
CFG>
https://pastebin.com/T37YjWmg

**Comment by nuclearsilo583** [comment]
I see you're missing the "team" config for the player skin.
Put it a "team". 2 is Ts 3 is CTs 4 for both.

**Comment by Lund1337** [comment]
And you were right!, now everything works.

**Comment by Lund1337** [comment]
Also, where i could get models/items/cs_gift.mdl?

**Comment by nuclearsilo583** [comment]
That model is located in css pak01_dir.vpk
Since you're usign csgo just use crate in the config example.
