### ISSUE TITLE
Problem with "steam" parameter selling exclusive itens

### ISSUE THREAD

**Issue by exd02** [nuclearsilo583/zephyrus-store-preview-new-syntax#109]
```
"Shrek (Comum)"
{
	"model"		"models\player\custom_player\kuristaja\shrek\shrek.mdl"
	"arms"		"models\player\custom_player\kuristaja\shrek\shrek_arms.mdl"
	"unique_id"	"uid_model_shrek"
	"team"		"3"
	"preview"	"1"
	"price"		"10"
	"type"		"playerskin"
	"skin"		"0"
	"body"		"25"

	// "steam"	"STEAM_0:0:510551677"
}
```
As you can see in the screenshot bellow, I can buy the item.
![image](https://user-images.githubusercontent.com/62575526/188293794-03311d62-938c-4294-854e-cd157a2ee2b8.png)

After uncommenting the "steam" parameter I can't buy the item anymore
```
"Shrek (Comum)"
{
	"model"		"models\player\custom_player\kuristaja\shrek\shrek.mdl"
	"arms"		"models\player\custom_player\kuristaja\shrek\shrek_arms.mdl"
	"unique_id"	"uid_model_shrek"
	"team"		"3"
	"preview"	"1"
	"price"		"10"
	"type"		"playerskin"
	"skin"		"0"
	"body"		"25"

	"steam"		"STEAM_0:0:510551677" // that's my steam id - https://steamid.uk/profile/76561198981369082
}
```
![image](https://user-images.githubusercontent.com/62575526/188293804-e0225340-641b-460f-80af-5ff733a0406b.png)

**Comment by exd02** [comment]
Am I doing something wrong or what?

**Comment by originalaidn** [comment]
Hi, try with this steam id:
STEAM_1:0:510551677

**Comment by nuclearsilo583** [comment]
There're 2 type of steam STEAM_1 and STEAM_0. If you get steamid from any get steamid website. Try to change that value between both cases.

**Comment by exd02** [comment]
Thaks!
Worked with the `STEAM_1:0:510551677`
