### ISSUE TITLE
Players can sell lootbox items

### ISSUE THREAD

**Issue by ardahzr** [nuclearsilo583/zephyrus-store-preview-new-syntax#11]
What can I do to prevent this?

**Comment by nuclearsilo583** [comment]
The sell option is already define by default by the core plugins. If they sell the lootbox the cash back only = buy_price*sell_ratio.
p/s: If you want to have a keyvalue to enable selling method. Please reply yes on next comment. I will try to create one

**Comment by ardahzr** [comment]
Yes please. Don't let them sell what they get out from loot box.
