### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by Villads1** [nuclearsilo583/zephyrus-store-preview-new-syntax#114]
I believe most things work fine but theres a few plugins that put out this error when compiling:

"error 017: undefined symbol "g_cvarChatTag""

I run latest Sourcemod & Metamod if that is useful. Thanks in advance.

**Comment by nuclearsilo583** [comment]
update your store.inc and remove g_cvarChatTag function in module/sp you compile since that function is not being used in latest chat-processor version.

**Comment by nuclearsilo583** [comment]
They are the same but different in how organize it. Store.sp split function into multiple files, store_combine.sp contain all the function in 1 files.
