### ISSUE TITLE
chat-processor.sp

### ISSUE THREAD

**Issue by oqyh** [nuclearsilo583/zephyrus-store-preview-new-syntax#117]
Line [#172](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/bf5f87a0240e20a1cd6b1a48c2f6d7e913ab66a7/addons/sourcemod/scripting/chat-processor.sp#L171)

```
return Plugin_Continue;
```

Line [#509](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/bf5f87a0240e20a1cd6b1a48c2f6d7e913ab66a7/addons/sourcemod/scripting/chat-processor.sp#L509)

```
return 0;
```

+ Add me on discord i have final fix for overlap gloves custom skins tested on my server + 20 servers All of it has no problems
Gold KingZ#1337

Keep up <3

**Comment by azalty** [comment]
> + Add me on discord i have final fix for overlap gloves custom skins tested on my server + 20 servers All of it has no problems

Why don't you share it here?
