### ISSUE TITLE
Issues with custom weapon models

### ISSUE THREAD

**Issue by Villads1** [nuclearsilo583/zephyrus-store-preview-new-syntax#123]
I have 2 problems with the custom weapon models.

1. Dropped models dont work - i have tried with many models all of which should work but on drop the gun goes back to default.

2. Some skins/models have problems with downloading as it wont download all of the files required to make the model work even with all the files on both server & fastdl. It does not even try to download .vvd .vtx or .phy files - no errors on the fastdl either.

3. Random question, how do i set an items lifespan to infinite? Is it just 0?

**Comment by nuclearsilo583** [comment]
1. Make sure you and your server have the .mdl files. And the files must be precached on map start. And also make sure you tiled them in correct weapon_ entities.
2. Check your cl_allowdownload and cl_allowupload both 1. And sv_allowupload and sv_allowdownload both set to 1 in the server. And you have a proper plugin that precache those files correctly. Also the server MUST have those files.
3. Just dont apply "Plans" config and it should work.

**Comment by nuclearsilo583** [comment]
What version of fpmvi you installed. make sure you install the one from my github page not from the franug's github.
