### ISSUE TITLE
Failed to read configs/store/earnings.txt

### ISSUE THREAD

**Issue by Caaine** [nuclearsilo583/zephyrus-store-preview-new-syntax#127]
Game: CSGO

didn't work for me 

"/csgo/addons/sourcemod/configs/store/earnings.txt" is the path

[SM] Exception reported: Failed to read configs/store/earnings.txt
[SM] Blaming: store/store_misc_earnings.smx
[SM] Call stack trace:
[SM]   [0] SetFailState
[SM]   [1] Line 1116, store_misc_earnings.sp::LoadConfig
[SM]   [2] Line 159, store_misc_earnings.sp::OnPluginStart
[SM] Unable to load plugin "store/store_misc_earnings.smx": Error detected in plugin startup (see error logs)

**Comment by azalty** [comment]
- You don't have the file or it is not formatted correctly
- You didn't give permissions to srcds to read the file
