### ISSUE TITLE
I can't able to use spray ingame

### ISSUE THREAD

**Issue by linuxuser12** [nuclearsilo583/zephyrus-store-preview-new-syntax#13]
items.txt
"Sprays"
	{
   	 "Aces High"
    	{
        "material" "materials/decals/franug/aces_high.vmt"
        "price" "300"
        "type" "spray"
	}
    
    "Banana"
    {
        "material" "materials/decals/franug/banana.vmt"
        "price" "300"
        "type" "spray"
    }
    
    
    "Blitzkrieg"
    {
        "material" "materials/decals/franug/blitzkrieg.vmt"
        "price" "300"
        "type" "spray"
    }
    
    "Bomb Doge"
    {
        "material" "materials/decals/franug/bomb_doge.vmt"
        "price" "300"
        "type" "spray"
    }
    
    "Doomed"
    {
        "material" "materials/decals/franug/doomed.vmt"
        "price" "300"
        "type" "spray"
    }
    
    "Drug War Veteran"
    {
        "material" "materials/decals/franug/drugwarveteran.vmt"
        "price" "300"
        "type" "spray"
    }
    
    "Hamster Hawk"
    {
        "material" "materials/decals/franug/hamster_hawk.vmt"
        "price" "300"
        "type" "spray"
    }
    
    "Headhunter"
    {
        "material" "materials/decals/franug/headhunter.vmt"
        "price" "300"
        "type" "spray"
    }
    
    "Headshot Guarantee"
    {
        "material" "materials/decals/franug/headshot_guarantee.vmt"
        "price" "300"
        "type" "spray"
    }
    
    "Just Trolling"
    {
        "material" "materials/decals/franug/just_trolling.vmt"
        "price" "300"
        "type" "spray"
    }
but when i equip them ingame they didn't work (i am using e to apply the spray)
Files are in fastdl too

**Comment by linuxuser12** [comment]
they are shown in preview perfectly

**Comment by nuclearsilo583** [comment]
Please try stay closer to a wall or try to spray on another wall materials.
If it doesnt work please use S_Downloader to precache material.

**Comment by linuxuser12** [comment]
i precached sprays still it is not working what's the bind to spray  in game

**Comment by eternity19** [comment]
same for me but anyway i will wait valve to fix it

**Comment by nuclearsilo583** [comment]
Hello, Hi it has been a long time
Sorry that the version i updated on github was a bit different from my offline test server.
Everything should be fix now.
Sorry for convenient.
You can find the fixed version [here](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/scripting/store_item_sprays.sp). Try it
If everything is fine please reply, and happy to close issue. 
Thanks
