### ISSUE TITLE
Combine store to work Shavit bhop 2.6.0

### ISSUE THREAD

**Issue by rambatenn** [nuclearsilo583/zephyrus-store-preview-new-syntax#14]
Hey,

Would be awesome if you would add this store working with bhop shavit timer. Now it doesn't printchat store messages but works in server. Got told you need add shavit include store.sp and shavitstyle chat printing. I don't know so much coding to myself to fix store.sp.

**Comment by nuclearsilo583** [comment]
Oh, I will rework this soon

**Comment by rambatenn** [comment]
That would be highly appreaciated. Amazing job btw people likes your store in servers i run.

**Comment by nuclearsilo583** [comment]
Can I ask you want to give credits for player who finish the map with shavit bhop timer?

**Comment by rambatenn** [comment]
That would be nice plus for it.

**Comment by nuclearsilo583** [comment]
Sorry for being late. My city has problem with covid-19 and I was really dont have free time.
But I now its ok.
For the bhop timer. First you need download the original plugin from [this](https://forums.alliedmods.net/showthread.php?p=2674332). Download zephyrus version. Then go scripting, compile the .sp with my include file (store.inc). And install anything as normal. It will compile fine without any problem and should work

**Comment by rambatenn** [comment]
thanks for it..Just fastly installed in my server but there is still the problem for general that store messages wont be  printed on server about store and getting credits on chat.

**Comment by nuclearsilo583** [comment]
The online credits should be sent to client once they earn it. And for the give credits by admin message you can take a look at this [cvar](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/cfg/sourcemod/plugin.store.cfg#L255)
