### ISSUE TITLE
The server crashed inexplicably after enabling the model

### ISSUE THREAD

**Issue by Max66888** [nuclearsilo583/zephyrus-store-preview-new-syntax#142]
I completely reinstalled the latest sm1.11. I did not add the plug-in, but only installed the store. After loading the model, the preview and the third person can be used normally, but the arm can not be displayed normally. When I was 
 equipment skin, the arm became the default arm of T, and the third person is working. I did not install other plug-ins except the store, which was not modified, and then the source code was compiled directly, If I re-enter the server without any modifications, it will crash, as follows
![image](https://user-images.githubusercontent.com/101586089/217310919-75130504-17e4-4344-88ff-be68f3ab6706.png)
![image](https://user-images.githubusercontent.com/101586089/217312487-723a4d5b-2bb5-4f50-a095-249940f64537.png)
This is when I am not equipped with skin
![image](https://user-images.githubusercontent.com/101586089/217312871-e0df987b-35b6-4719-9508-386f802ba459.png)
This is when I am equipped with skin and thirdperson
![image](https://user-images.githubusercontent.com/101586089/217312951-9a666dcc-c673-4428-a629-4e29eb1592f1.png)
![image](https://user-images.githubusercontent.com/101586089/217313076-65121cbd-f1c8-4cda-8015-4c009b5f460c.png)

**Comment by Max66888** [comment]
When I restart the server after installing the skin, it will cause the server above to crash

**Comment by nuclearsilo583** [comment]
The playerskin modules will sometime have its precache model scripts timeout if you add too many. I bet you should install another 3rd precache plugin to deal with model precache on map start.

**Comment by Max66888** [comment]
> The playerskin modules will sometime have its precache model scripts timeout if you add too many. I bet you should install another 3rd precache plugin to deal with model precache on map start.
> And please install N arms fix with Kxnrl's arms fix extension to remove the CTs custom sleeve that overlap with custom arms.

Is it possible that this is a bug? Because there is only one model in my item list, I have installed two arm fix plug-ins, but they still cannot work, and my hands will disappear directly.

**Comment by nuclearsilo583** [comment]
what is your sm exts list and meta list. Also do you have any log of the crash.

**Comment by Max66888** [comment]
The original problem has been solved, thank the author
