### ISSUE TITLE
Store missing menu items

### ISSUE THREAD

**Issue by ppzinx** [nuclearsilo583/zephyrus-store-preview-new-syntax#146]
hello, 
At first everything was fine, menu was full of options then i don't know where i messed up. 
The menu showed just the Accessories option and it's glitched.

I reinstalled the full store plugin with all Resources and i keep running into this problem.

help?

screenshot: https://ibb.co/25WZttS
![20230210165941_1 – kopija](https://user-images.githubusercontent.com/125059566/218138750-8324530b-3d8c-49a7-9663-195a829faf0e.jpg)

**Comment by Max66888** [comment]
Please show your items.txt

**Comment by ppzinx** [comment]
here's my items.txt file:

[items.txt](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/files/10709609/items.txt)

**Comment by ppzinx** [comment]
now i managed to get it work a bit more but everything is broken
![Screenshot_276](https://user-images.githubusercontent.com/125059566/218190860-c3616bf5-e84b-4677-a188-709bcdf596ec.png)

when i open shop toplist from menu nothing shows only over !storetop it shows up


when i open Accessories i get this menu and it's functions are broken
![Screenshot_277](https://user-images.githubusercontent.com/125059566/218191185-d5c26bce-4a2a-4482-9f2a-cf239bbb975b.png)

fun & Entertain shows only one option
![Screenshot_278](https://user-images.githubusercontent.com/125059566/218191436-ff404bfe-e846-45ee-8086-46d4e484618c.png)

**Comment by ppzinx** [comment]
sorry i forgot to compile all plugins for store now i have menu like this
https://files.fm/u/3fdd9586a#/view/ce2zhpjxt

and what is with that store crash countdown

**Comment by Max66888** [comment]
> sorry i forgot to compile all plugins for store now i have menu like this
> https://files.fm/u/3fdd9586a#/view/ce2zhpjxt
> 
> error log
> 
> L 02/10/2023 - 23:17:09: [store.smx] SQL error happened.
> Query: delete `store_items`, `store_equipment`from  `store_items`, `store_equipment` where (store_items.unique_id = store_equipment.unique_id) and store_items.date_of_expiration<>0 and store_items.date_of_expiration<1676067429
> Error: near "`store_items`": syntax error

You need to add unique ids to all the required items and then make sure that your plugins are writing to the database properly?

**Comment by ppzinx** [comment]
menu fixed

**Comment by Max66888** [comment]
> menu fixed

So is it consistent with my description?
