### ISSUE TITLE
Say sounds Module Request

### ISSUE THREAD

**Issue by linuxuser12** [nuclearsilo583/zephyrus-store-preview-new-syntax#15]
is there any way to add sounds to store so that people have to purchase them and then use the sound

**Comment by nuclearsilo583** [comment]
First of all. Thank you for using my code. 
This module will be developed soon. Stay tuned

**Comment by linuxuser12** [comment]
can you add me on steam please
https://steamcommunity.com/id/0xhexsploit

**Comment by nuclearsilo583** [comment]
Sorry for being late. 
My city have some problem with covid-19 and I really dont have time.
But now say sound is on. You can use it [here](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/scripting/store_item_saysound.sp)
