### ISSUE TITLE
How i change default player model ?

### ISSUE THREAD

**Issue by linuxuser12** [nuclearsilo583/zephyrus-store-preview-new-syntax#16]
You have commented //g_cvarSkinForceChangeCT = RegisterConVar("sm_store_playerskin_default_ct", "", "Path of the default CT skin.", TYPE_STRING);
When i try to uncomment this line it throws error

**Comment by nuclearsilo583** [comment]
Currently the default skin is disabled. If you want to use the default model. I will re-enable it on new commit

**Comment by linuxuser12** [comment]
can you please enable it 
it will be helpful for so many people

**Comment by nuclearsilo583** [comment]
I re-enabled the default skin for playerskin module. Check [here](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/scripting/store_item_playerskins_no_zr_version.sp)

**Comment by linuxuser12** [comment]
Thanks mate :D
