### ISSUE TITLE
[CS:GO] "sm_store_chat_tag_plugins" cvar problem

### ISSUE THREAD

**Issue by Ketz1337** [nuclearsilo583/zephyrus-store-preview-new-syntax#162]
Messages are not preceded by "[Store] ".

![Screenshot_3](https://user-images.githubusercontent.com/23225942/235312248-310bb151-3bb5-40f2-8607-8d67d88b21e3.png)

Am I doing something wrong?

**Comment by azalty** [comment]
I think I might have identified the problem. Can you try changing `sm_store_chat_tag_plugins` to something else, then back to "[Store] " again, and see if it works?

**Comment by azalty** [comment]
> I typed in console: sm_rcon sm_store_chat_tag_plugins "Test "
Restarted the map.
Now the "[Store ] " text works.

Did it show [Store] or Test?

Also, which version of the plugin are you running?

**Comment by azalty** [comment]
no, the master branch is more up to date, but the latest confirmed to be working version is the release.

I'm personally on a modified 7.0.4 version. I'll try to switch to the latest version to see if I can reproduce this, and I'll continue checking the code.

---

Currently, the tag is cached in a variable. This variable caches the tag when the convar linked to it is modified, but it might not be modified if it is the same as the default value. Changing the tag to something else, then back to "[Store] " WITHOUT changing maps should also work if I'm correct.

This "temporary fix" will cease to work when the server is restarted OR the plugin is reloaded. It should survive map changes.
