### ISSUE TITLE
say sounds

### ISSUE THREAD

**Issue by eternity19** [nuclearsilo583/zephyrus-store-preview-new-syntax#17]
How can i equip more sounds one time?

**Comment by nuclearsilo583** [comment]
You dont need to equip the sound to use. 
When ever you chat any words related to the "trigger" config. It will automatically check to make sure that you must have the item so it can emit the sound. [Code](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/scripting/store_item_saysound.sp#L301)
