### ISSUE TITLE
SaySounds Help

### ISSUE THREAD

**Issue by linuxuser12** [nuclearsilo583/zephyrus-store-preview-new-syntax#19]
How do i use Saysound in store?
i don't wanna use trigger word.i want to use sounds from store

**Comment by linuxuser12** [comment]
https://drive.google.com/file/d/1hvuiJVyubWJav1MI0vrrTOo4TjQdjrVF/view
like this

**Comment by S1ncer3ly** [comment]
im having the same issue in my server please help asap 
thankyou

**Comment by nuclearsilo583** [comment]
I re-added in-store use for say sound. Now you can use it with chat trigger or in-store without any problem.
If you have any question feel free to ask me

**Comment by linuxuser12** [comment]
Thanks i'll test it and get back to you

**Comment by linuxuser12** [comment]
Didn't worked 
it would be great if we continue the conversation on Discord:-
Hexsploit0x01#6398

**Comment by nuclearsilo583** [comment]
Please check discord.
