### ISSUE TITLE
Doubt with cvar generated sm_store_custom_credits

### ISSUE THREAD

**Issue by crashzk** [nuclearsilo583/zephyrus-store-preview-new-syntax#25]
The **`plugin.store.cfg`** file located in the **`cfg/sourcemod`** folder has a cvar that came configured/generated like this:
```
// Flag and multiplier of income credits [credits = multiplier*base_creadit)
// -
// Default: "o 6"
sm_store_custom_credits o 6.0
```
In case I would like to know if this cvar is right? Or should I set it by when it will be multiplied directly, like **`sm_store_custom_credits "6.0"`**

**Comment by nuclearsilo583** [comment]
those cvar are set for multiple credit for player have certain flag.
Usage: sm_store_custom_credits <flag> <multiply>
Example: sm_store_custom_credits "op" "2.0" Player with o and p flag will have double income for all event.
