### ISSUE TITLE
Message being sent alone / Player invisible

### ISSUE THREAD

**Issue by crashzk** [nuclearsilo583/zephyrus-store-preview-new-syntax#3]
After I installed the plugin it is sending a message to the server, but it is blank, it just shows that an ADM sent a message:

![image](https://user-images.githubusercontent.com/32937653/111487639-4c5b9500-8717-11eb-9a16-6ffffd2b90fe.png)
As you can see on the print, there are my messages and another one that keeps sending only at all times.

No error logs, and plugin all right apparently.
```
[SM] Listing 55 plugins:
  01 "[ANY] Chat Responder" (1.3.4) by Headline
  02 "hextags" (2.03) by Hexah
  03 "SM FPVMI - Custom Weapons Menu" (3.1) by Franc1sco franug
  04 "Fortnite player hits" (1.2.0) by GAMMA CASE
  05 "Admin Help" (1.10.0.6502) by AlliedModders LLC
  06 "Simple Chat Processor (Redux)" (2.3.0fix) by Simple Plugins, Mini
  07 "Basic Ban Commands" (1.10.0.6502) by AlliedModders LLC
  08 "[VIP] COIN" (2.0.1) by Pheonix (˙·٠●Феникс●٠·˙) & R1KO, pracc
  09 "[VIP] MKIT" (1.1.3) by Pheonix (edit Felya)
  10 "[VIP] Stats" (2.6) by R1KO 
  11 "[VIP] FakeRank" (1.0.2) by TiNiK
  12 "[VIP] Admin Privileges" (1.1.1) by R1KO, vadrozh, CrazyHackGUT aka Kruzya
  13 "[VIP] Admin" (1.1.1) by R1KO, vadrozh, -
  14 "[VIP] PaintBall" (1.0) by FrozDark (HLModders LLC) (rework by SHKIPPERBEAST)
  15 "Sound Commands" (1.10.0.6502) by AlliedModders LLC
  16 "Admin Menu" (1.10.0.6502) by AlliedModders LLC
  17 "Basic Commands" (1.10.0.6502) by AlliedModders LLC
  18 "SM First Person View Models Interface" (3.2) by Franc1sco franug
  19 "Rock The Vote" (1.10.0.6502) by AlliedModders LLC
  20 "Advanced Parachute" (1.0fix) by ESK0, crashzk
  21 "Map Nominations" (1.10.0.6502) by AlliedModders LLC
  22 "[VIP] Core" (3.1 DEV) by R1KO
  23 "AFK Manager" (4.3.0) by Rothgar
  24 "[ ZK Servidores™ ] Block Commands" (1.1) by Geison, crashzk
  25 "[PTaH] Block SM Plugins" (1.0.0) by Bara
  26 "Basic Votes" (1.10.0.6502) by AlliedModders LLC
  27 "Basic Info Triggers" (1.10.0.6502) by AlliedModders LLC
  28 "Chat-Processor" (2.2.8) by Drixevel
  29 "[ ZK Servidores™ ] Console Ads" (1.1) by biielzk, crashzk
  30 "Admin File Reader" (1.10.0.6502) by AlliedModders LLC
  31 "Weapons & Knives" (1.7.1) by kgns | oyunhost.net
  32 "SM Voice Agents Enabler" (1.0) by Franc1sco franug
  33 "ServerAdvertisements3" (3.1.4) by ESK0
  34 "Basic Chat" (1.10.0.6502) by AlliedModders LLC
  35 "[Levels Ranks] Core" (v3.1.6) by RoadSide Romeo & Wend4r
  36 "Client Preferences" (1.10.0.6502) by AlliedModders LLC
  37 "Fun Commands" (1.10.0.6502) by AlliedModders LLC
  38 "Fun Votes" (1.10.0.6502) by AlliedModders LLC
  39 "Gloves" (1.0.5) by kgns | oyunhost.net
  40 "Reserved Slots" (1.10.0.6502) by AlliedModders LLC
  41 "MapChooser" (1.10.0.6502) by AlliedModders LLC
  42 "Basic Comm Control" (1.10.0.6502) by AlliedModders LLC
  43 "Anti-Flood" (1.10.0.6502) by AlliedModders LLC
  44 "SM Franug CS:GO Agents Chooser" (1.2) by Franc1sco franug & Romeo
  45 "Player Commands" (1.10.0.6502) by AlliedModders LLC
  46 "Nextmap" (1.10.0.6502) by AlliedModders LLC
  47 "Store - The Resurrection with preview rewritten compilable with SM 1.10" (5.0) by Zephyrus, nuclear silo
  48 "Store - Zombie:Reloaded Player Classes Module" (1.0) by nuclear silo
  49 <Failed> "Store - Player Skin module" (1.0) by nuclear silo
  50 "Store - Pet item module" (1.0) by nuclear silo
  51 "Store - MVP sound item module" (1.0) by shanapu, nuclear silo
  52 "Store - Roulette gamble module" (1.0) by shanapu, nuclear silo
  53 "Store - Jackpot gamble module" (1.0) by shanapu, nuclear silo
  54 "Store - Crowns gamble module" (1.0) by shanapu, nuclear silo
  55 "Store - Link item module" (1.0) by shanapu, nuclear silo
Errors:
store/store_item_playerskins.smx (Store - Player Skin module): Native "ZR_IsClientZombie" was not found
```
[errors_20210317.log](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/files/6157292/errors_20210317.log)

**Comment by crashzk** [comment]
Another demo with a much higher score and I can download it normally.

https://sqlmatches.com/c/ZKServidores/scoreboard/07743911-7907-4067-a4e7-d8f5ad0c9376

**Comment by crashzk** [comment]
Another demo with a much higher score and I can download it normally.

https://sqlmatches.com/c/ZKServidores/scoreboard/07743911-7907-4067-a4e7-d8f5ad0c9376

**Comment by nuclearsilo583** [comment]
Try reverse back to version 2.2.1 of chat processor. The newest version of Chat Processor cause this problem.
The version 2.2.1 is already included in the master branch

**Comment by crashzk** [comment]
> Try reverse back to version 2.2.1 of chat processor. The newest version of Chat Processor cause this problem.
> 
> The version 2.2.1 is already included in the master branch
> 
> Known bug and I dont know how to fix. Sometime if you config player name tag such as: {green} AnyTag. Chat hook will show like: (color green) AnyTag (still green not team color) playername: (message). Maybe you need to find someone to fix this problem.

Strange, I always used the latest version of Chat-Processor, I never had this problem, I will leave the older version and see, thanks.


> For Player skins module error. If you dont use Zombie:Reloaded plugins please head to source code and comment the line in the picture and any related code.
> ![Untitled](https://user-images.githubusercontent.com/58926275/111531852-a1d78680-8797-11eb-96fc-2b961b48c0ba.png)

Thank you, I will test it too.

Anything I return contact.

**Comment by crashzk** [comment]
Just leaving feedback.

Chat Processor version 2.2.3 works fine: https://github.com/Drixevel/Chat-Processor/releases/tag/2.2.3

Without any error of invisible message so far.

But now it shows another error besides the Store Players Skins plugin.

```
Errors:
store/store_item_playerskins.smx: Native "ZR_IsClientZombie" was not found
store/store_item_hats.smx: Native "IsPlayerInTP" was not found
```
I didn't do anything to remove the error from ZR_, I just changed the Chat-Processor.

**Comment by nuclearsilo583** [comment]
I updated the non ZR version of player skin module for you check out [here](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/scripting/store_item_playerskins_no_zr_version.sp).
For hats module it need the origin thirdpersion plugin by zephyrus (I also updated to master) check [here](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/scripting/thirdperson.sp) or you can use the non third person plugins (note that if you use this version when you goes into thirdperson mode you cant see your own hats but others player can) [here](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/scripting/store_item_hats_no_thirdpersion.sp)

**Comment by crashzk** [comment]
> I updated the non ZR version of player skin module for you check out [here](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/scripting/store_item_playerskins_no_zr_version.sp).
> For hats module it need the origin thirdpersion plugin by zephyrus (I also updated to master) check [here](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/scripting/thirdperson.sp) or you can use the non third person plugins (note that if you use this version when you goes into thirdperson mode you cant see your own hats but others player can) [here](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/scripting/store_item_hats_no_thirdpersion.sp)

Thank you I will test everything. One more thing, does support for **`store-trade.smx`** still work, just send the plugin

**Comment by nuclearsilo583** [comment]
> Thank you I will test everything. One more thing, does support for **`store-trade.smx`** still work, just send the plugin

Yes, as the original code if from zephyrus's store so any module that made or are being made still be able to use without any error.
You can have the store-trade.smx in zephyrus's store post on alliedmod

**Comment by crashzk** [comment]
Come on, all plugins are working, thanks.
```
[SM] Listing 59 plugins:
  01 "[ANY] Chat Responder" (1.3.4) by Headline
  02 "hextags" (2.03) by Hexah
  03 "SM FPVMI - Custom Weapons Menu" (3.1) by Franc1sco franug
  04 "Fortnite player hits" (1.2.0) by GAMMA CASE
  05 "Admin Help" (1.10.0.6502) by AlliedModders LLC
  06 "Simple Chat Processor (Redux)" (2.3.0fix) by Simple Plugins, Mini
  07 "Basic Ban Commands" (1.10.0.6502) by AlliedModders LLC
  08 "[VIP] COIN" (2.0.1) by Pheonix (˙·٠●Феникс●٠·˙) & R1KO, pracc
  09 "[VIP] MKIT" (1.1.3) by Pheonix (edit Felya)
  10 "[VIP] Stats" (2.6) by R1KO 
  11 "[VIP] FakeRank" (1.0.2) by TiNiK
  12 "[VIP] Admin Privileges" (1.1.1) by R1KO, vadrozh, CrazyHackGUT aka Kruzya
  13 "[VIP] Admin" (1.1.1) by R1KO, vadrozh, -
  14 "[VIP] PaintBall" (1.0) by FrozDark (HLModders LLC) (rework by SHKIPPERBEAST)
  15 "Sound Commands" (1.10.0.6502) by AlliedModders LLC
  16 "Admin Menu" (1.10.0.6502) by AlliedModders LLC
  17 "Basic Commands" (1.10.0.6502) by AlliedModders LLC
  18 "SM First Person View Models Interface" (3.2) by Franc1sco franug
  19 "Rock The Vote" (1.10.0.6502) by AlliedModders LLC
  20 "Advanced Parachute" (1.0fix) by ESK0, crashzk
  21 "Map Nominations" (1.10.0.6502) by AlliedModders LLC
  22 "Store - The Resurrection with preview rewritten compilable with SM 1.10 new syntax" (5.6) by Zephyrus, nuclear silo
  23 "[VIP] Core" (3.1 DEV) by R1KO
  24 "AFK Manager" (4.3.0) by Rothgar
  25 "[ ZK Servidores™ ] Block Commands" (1.1) by Geison, crashzk
  26 "[PTaH] Block SM Plugins" (1.0.0) by Bara
  27 "Thirdperson | Mirrow Mode" (1.11) by Zephyrus
  28 "Basic Votes" (1.10.0.6502) by AlliedModders LLC
  29 "Basic Info Triggers" (1.10.0.6502) by AlliedModders LLC
  30 "Chat-Processor" (2.2.3) by Drixevel
  31 "[ ZK Servidores™ ] Console Ads" (1.1) by biielzk, crashzk
  32 "Admin File Reader" (1.10.0.6502) by AlliedModders LLC
  33 "Weapons & Knives" (1.7.1) by kgns | oyunhost.net
  34 "SM Voice Agents Enabler" (1.0) by Franc1sco franug
  35 "Nextmap" (1.10.0.6502) by AlliedModders LLC
  36 "ServerAdvertisements3" (3.1.4) by ESK0
  37 "store/store_item_playerskins_no_zr_version.smx"
  38 "Store - Pet item module" (1.0) by nuclear silo
  39 "Store - MVP sound item module" (1.0) by shanapu, nuclear silo
  40 "Store - Chat Processor item module" (1.0) by nuclear silo
  41 "Store - Roulette gamble module" (1.0) by shanapu, nuclear silo
  42 "store/store_item_hats.smx"
  43 "Store - Trade System" (1.0) by Zephyrus
  44 "Store - Jackpot gamble module" (1.0) by shanapu, nuclear silo
  45 "Store - Crowns gamble module" (1.0) by shanapu, nuclear silo
  46 "Store - Link item module" (1.0) by shanapu, nuclear silo
  47 "Store Custom Weapon Models" (3.0) by Mr.Derp & Franc1sco franug | Zephyrus Store Module & bbs.93x.net
  48 "Basic Chat" (1.10.0.6502) by AlliedModders LLC
  49 "[Levels Ranks] Core" (v3.1.6) by RoadSide Romeo & Wend4r
  50 "Client Preferences" (1.10.0.6502) by AlliedModders LLC
  51 "Fun Commands" (1.10.0.6502) by AlliedModders LLC
  52 "Fun Votes" (1.10.0.6502) by AlliedModders LLC
  53 "Gloves" (1.0.5) by kgns | oyunhost.net
  54 "Reserved Slots" (1.10.0.6502) by AlliedModders LLC
  55 "MapChooser" (1.10.0.6502) by AlliedModders LLC
  56 "Basic Comm Control" (1.10.0.6502) by AlliedModders LLC
  57 "Anti-Flood" (1.10.0.6502) by AlliedModders LLC
  58 "SM Franug CS:GO Agents Chooser" (1.2) by Franc1sco franug & Romeo
  59 "Player Commands" (1.10.0.6502) by AlliedModders LLC
  ```
I left these only disabled since I do not use these game modes.
  
![image](https://user-images.githubusercontent.com/32937653/111793655-3c24f080-88a4-11eb-849f-7adf527e5ddd.png)

Now just to finish with the doubts.

What would this command do:
```
"Main Info Panel"
	{
		"Shop TOP Lists"
		{
			"command"		"sm_storetop"
			"unique_id"		"uid_toplists_toplists"
			"type"			"link"
		}
	}
```
I use it and nothing happens.

It would also have the materials and models of the pet **Tiny Haipa**:
```
"Tiny Haipa"
		{
			"model" 		"models/maoling/pet/misc/haipa/haipa_v2.mdl"
			"position" 		"25.0 -20.0 0.0"
			"angles" 		"0.0 340.0 0.0"
			"idle" 			"ACT_DOTA_IDLE"
			"idle2" 		"ACT_DOTA_IDLE_RARE"
			"run" 			"ACT_DOTA_RUN"
			"preview"		"1"
			"trade" 		"4"	
			"unique_id"		"uid_pet_tiny_haipa"
			"type" 			"pet"
			"price" "350"
```
He was left with just a giant square of error, it must be because he didn't have it on the server, so I don't download it.

I also noticed that even configured in the store the category of player skins does not show in the store menu on the server. Attached is the store config that I use on the server.
  
[items.txt](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/files/6171744/items.txt)

**Comment by nuclearsilo583** [comment]
Lets me fix your issue one by one.
1. store_item_playerskins_no_zr_version.smx I removed the precache on models to prevent client crash (random player will have this issue), if they dont crash. They will issue on the materials precache error so they will have their fps drop. To manually precache custom models and materials. Please install this [plugin](https://forums.alliedmods.net/showthread.php?p=2337905).
2. The link type item mean player will use a command on shop (such as !knife or !ws with prefix !sm_(command)). The command on my config mean player store top credits using [this](https://forums.alliedmods.net/showthread.php?p=2703316) plugins.
3. The haipa models and materials. I updated on the master. Please redownload
4. If player or any person have issue with the square error box. It means they're missing models file. Install all materials and models to your game server and update everything into your fastdl server. I already made bz2 for you. Download on master for pet. And also you need to precache all custom materials and models or your server will be crashed. Download auto precache plugins at (1).
5. If player skin does not show in the store menu. It mean your server down have this models. Install the models and all the related materials to your gamesever. 
p/s: If you have any question feel free to ask

**Comment by crashzk** [comment]
Good, thanks.

I will be closing these issues, but I will be testing everything, thanks again. Any problem I open an issues with the error just so as not to pollute several subjects just in this one.

**Comment by crashzk** [comment]
Just passing by to warn, all right, working that it is a beauty.

And about PET, I loved it. Hahaha
