### ISSUE TITLE
Best way to migrate Sqlite to MySQL for Store.

### ISSUE THREAD

**Issue by mudkipmayukh** [nuclearsilo583/zephyrus-store-preview-new-syntax#37]
Can someone help me in migrating SQLite database to MySQL for this store?

**Comment by originalaidn** [comment]
Hi.
Try to use SQLiteStudio: https://sqlitestudio.pl/
Or this site: https://www.rebasedata.com/convert-sqlite-to-mysql-online

**Comment by nuclearsilo583** [comment]
Close due to inactive for a time
