### ISSUE TITLE
Menu not working

### ISSUE THREAD

**Issue by Falow1** [nuclearsilo583/zephyrus-store-preview-new-syntax#41]
I have compiled the original plugin version and the version for TF2 which is the game I want to put the plugin, I tried to use the TF2 version first but the !shop/!inventory menu commands don't show up although there is no error when compiling, then I tried the original version and it doesn't work, can anyone help me?

Edit: The chat shows things like "You earned x credits" and the "!gift" command works.

**Comment by originalaidn** [comment]
Did you compiled store_item_xyz (check with tf2 modules) to the server or you compiled only the core (store.sp)?

If you compiled the core and item modules need server restart or store reload.

**Comment by Falow1** [comment]
I can't mess with it now, but I will try it later and let you know the result, thanks

> Did you compiled store_item_xyz (check with tf2 modules) to the server or you compiled only the core (store.sp)?
> 
> If you compiled the core and item modules need server restart or store reload.

I can't mess with it now, but I'll try it later and let you know the result, thanks!

**Comment by Falow1** [comment]
> Did you compiled store_item_xyz (check with tf2 modules) to the server or you compiled only the core (store.sp)?
> 
> If you compiled the core and item modules need server restart or store reload.

Well I compiled both, tested both by restarting the server for each change but it didn't work

**Comment by originalaidn** [comment]
What item module you try?
Because need to add the item in:
addons/sourcemod/configs/store/items.txt

**Comment by Falow1** [comment]
> What item module you try? Because need to add the item in: addons/sourcemod/configs/store/items.txt

I tried the tf2 item modules, added what I wanted in "items.txt"(just trails and chat tags) and it doesn't work, I was taking a look and it seems that it just doesn't show the inventory and store menu, all the other commands that the plugin offers work n

**Comment by nuclearsilo583** [comment]
Please do following steps:
1. Check if that the module you want was compile and run successfuly.
2. Check error log or and log file.
3. Check if in your server directory has all the needed files (materials, models)
4. If nothing above is wrong please send your plugin list here via pastebin.com

**Comment by Falow1** [comment]
> Please do following steps:
> 
> 1. Check if that the module you want was compile and run successfuly.
> 2. Check error log or and log file.
> 3. Check if in your server directory has all the needed files (materials, models)
> 4. If nothing above is wrong please send your plugin list here via pastebin.com

Here is my plugin list: https://pastebin.com/hGxmbR3E

**Comment by nuclearsilo583** [comment]
I see there're no module install for your tf2 server. Please head to the `tf_module_rework` and install any module you like

**Comment by Falow1** [comment]
> Vejo que não há nenhum módulo instalado 

> I see there're no module install for your tf2 server. Please head to the `tf_module_rework` and install any module you like

So I need to compile these "store_item" and add, I'm a fool, thanks

**Comment by Falow1** [comment]
Worked, good plugin :)
