### ISSUE TITLE
Problems with trails

### ISSUE THREAD

**Issue by Falow1** [nuclearsilo583/zephyrus-store-preview-new-syntax#42]
I'm using the TF2 module but the trails don't show up, the files download normally .vmt and .vtf but the trails don't show up, can someone help me solve this if they know why. I am using the trail sprites from the original plugin

**Comment by nuclearsilo583** [comment]
I checked the module and tested on my server and I have no problem with it.
Please check if your materials 
.vmt file can be read with tf2 engine which is 7.2.

**Comment by Falow1** [comment]
> I checked the module and tested on my server and I have no problem with it. Please check if your materials .vmt file can be read with tf2 engine which is 7.2.

In my case I am using the trails from here https://github.com/dvarnai/store-plugin/tree/master/materials/sprites/store/trails , they are not compatible with the plugin? Sorry I don't know about this and my computer is broken so there is no way I can see about it for now

**Comment by nuclearsilo583** [comment]
original module from original store need to edit to be able to use in this store. All the most used module has been edited. Check the game module folder for your uses.

**Comment by Falow1** [comment]
> original module from original store need to edit to be able to use in this store. All the most used module has been edited. Check the game module folder for your uses.



> original module from original store need to edit to be able to use in this store. All the most used module has been edited. Check the game module folder for your uses.

I have the correct modulo to use trails, they are equipable but do not appear in the players

**Comment by nuclearsilo583** [comment]
Can you check if the version of your .vmt file is version 7.2

**Comment by Falow1** [comment]
> Can you check if the version of your .vmt file is version 7.2

I don't really know how to see the version of the .vmt file but I'll come back here if I can

**Comment by Falow1** [comment]
> Can you check if the version of your .vmt file is version 7.2

I was able to check the version and it is 7.2, do you have any other idea what it could be?

**Comment by nuclearsilo583** [comment]
Sorry I dont know what cause for your problem. So could you re-install store.sp and the trail module for TF2 in the tf2 module folder and try again.

**Comment by Falow1** [comment]
Ok then, thanks for the help

**Comment by Falow1** [comment]
I found out what it was, my server was set to sv_pure 2 so it wasn't working
