### ISSUE TITLE
This isnt an issue, im just wondering what modules currently work for css? And are there any plans in the future to rework more modules for css?

### ISSUE THREAD

**Issue by Saund7** [nuclearsilo583/zephyrus-store-preview-new-syntax#44]

**Comment by nuclearsilo583** [comment]
1. Current available for css: 
- module in `css_module_reworked`
- all gamble module 
- grenade skin/trail, trail
- bullet impact/spark/tracer, sprays
- hat
- saysound
- zr class (for zr server)
- earning
- math
- toplists
- giveaway
- info/link
2. Maybe
