### ISSUE TITLE
store_item_playerskins_no_zr_version_l4d2.sp compile errors (warning)

### ISSUE THREAD

**Issue by Cyber-Samurai-997** [nuclearsilo583/zephyrus-store-preview-new-syntax#45]
Hey, I just wanna report a log I got when compiling the module in _**_l4d2_modules_reworked**_ folder:
> //SourceMod Batch Compiler
// by the SourceMod Dev Team
//// store_item_playerskins_no_zr_version_l4d2.sp
//
// D:\GAMES\SERVER\L4D2 #TEST\left4dead2\addons\sourcemod\scripting\store_item_playerskins_no_zr_version_l4d2.sp(258) : warning 203: symbol is never used: "index"
// D:\GAMES\SERVER\L4D2 #TEST\left4dead2\addons\sourcemod\scripting\store_item_playerskins_no_zr_version_l4d2.sp(332) : warning 203: symbol is never used: "GetEquippedSkin"
// D:\GAMES\SERVER\L4D2 #TEST\left4dead2\addons\sourcemod\scripting\store_item_playerskins_no_zr_version_l4d2.sp(318) : warning 203: symbol is never used: "RemoveClientGloves"
// D:\GAMES\SERVER\L4D2 #TEST\left4dead2\addons\sourcemod\scripting\store_item_playerskins_no_zr_version_l4d2.sp(65) : warning 204: symbol is assigned a value that is never used: "GAME_TF2"
// Code size:            36456 bytes
// Data size:          1114328 bytes
// Stack/heap size:      16384 bytes
// Total requirements: 1167168 bytes
//
// 4 Warnings.
//
// Compilation Time: 0.27 sec
// ----------------------------------------
Press enter to exit ...

**Comment by nuclearsilo583** [comment]
Warning = plugin can run without any problem. You can ignore these

**Comment by originalaidn** [comment]
Hi, can check in my repo the store_item_playerskins_no_zr_version_l4d2 ?
No warning, but i don't know works or not, because i don't have L4D2 server.
