### ISSUE TITLE
error store_misc_giveaway_aidnversion.sp

### ISSUE THREAD

**Issue by oqyh** [nuclearsilo583/zephyrus-store-preview-new-syntax#49]
//// store_misc_giveaway_aidnversion.sp
//
// store_misc_giveaway_aidnversion.sp(180) : warning 209: function "CommandGiveaway" should return a value
// Code size:            28416 bytes
// Data size:             8024 bytes
// Stack/heap size:      16384 bytes
// Total requirements:   52824 bytes
//
// 1 Warning.
//
// Compilation Time: 0.22 sec

**Comment by oqyh** [comment]
store_misc_giveaway_aidnversion.sp 
[After Line 179](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/71204491f42c23053c5bc36617f16c63af9e7b02/addons/sourcemod/scripting/store_misc_giveaway_aidnversion.sp#L179)
```
	return Plugin_Continue;
```


https://pastebin.com/gjiS00Vr

**Comment by nuclearsilo583** [comment]
return Plugin_Handled; should be better
