### ISSUE TITLE
Thank you for your awesome work, some questions and suggestions

### ISSUE THREAD

**Issue by flashing1998** [nuclearsilo583/zephyrus-store-preview-new-syntax#5]
by fixing this plugin you are doing god's work, I can't thank you enough
there are some questions and suggestions

will these modules work with your version of store 
https://github.com/CrazySkull2k/CSGO-Arms-Fix or have already integrated this in your build
https://github.com/Cruze03/Store-Credits-for-Specified-Events
https://github.com/oylsister/Store-by-Zephyrus

also is there an estimated time in which you will add aura, particle, trails, say sounds support because its kinda important modules of store

also there are some suggestions that you can port to this store
there are some really cool modules for https://github.com/FD-Forks/Shop-Core 
like these 
https://hlmod.ru/resources/shop-colored-smoke.2082/
https://hlmod.ru/resources/lr-credits-multiplier.1318/
https://hlmod.ru/resources/shop-buy-vip.1885/
https://hlmod.ru/resources/vip-shop-discounts.109/

I know I am asking a lot and you may be a busy person but I just wanted to put it out there xD because i don't know how to code
thank you for your awesome work

**Comment by nuclearsilo583** [comment]
Sorry mate I dont have hlmod.ru account so I cant help anything at any module from SHOP-Core. As arm fix, specified event. Currently build is base from original zephyrus store which support giving extra credits for vip custom flag and credits on kill. You can use custom event credits for this. As for arm fix. I will test later.
- Yes aura, trail, etc.. will be supported soon in 2 days when I have free time
p/s: If you have hlmod.ru account you can share me 🍡

**Comment by flashing1998** [comment]
thank you for your response will be waiting for the release
and yes I have hlmod account I can provide you all the files you need
and I think arms fix will work with this plugin https://forums.alliedmods.net/showthread.php?t=293295

**Comment by nuclearsilo583** [comment]
New particle, aura, trail, tracers are now available to use.
For the shop-core modules. I will test it tomorrow

**Comment by flashing1998** [comment]
damm you are fast i thought i would take you some time
thanks
