### ISSUE TITLE
particle bug

### ISSUE THREAD

**Issue by Caaine** [nuclearsilo583/zephyrus-store-preview-new-syntax#53]
If you go into the spectator with a particle trail or aura, it still shows up in spectator 

![grafik](https://user-images.githubusercontent.com/13827296/162203386-911163e6-c2c2-4ff1-8754-08e74746205b.png)

**Comment by Caaine** [comment]
Particles not showing anymore in the Store Preview and when I'm on a team

**Comment by nuclearsilo583** [comment]
What team are you in and is the iten has preview 1 in the items.txt

**Comment by Caaine** [comment]
CT or T on both doesn't work and yes preview is on 1 without the fix it works

**Comment by nuclearsilo583** [comment]
Did you update the new store.sp. If you did try to use the previous version and try again

**Comment by Caaine** [comment]
sry.. failed.. compiled the new store.sp and it's working

**Comment by nuclearsilo583** [comment]
Glad to hear that
