### ISSUE TITLE
Database character table compatibility problem

### ISSUE THREAD

**Issue by Max66888** [nuclearsilo583/zephyrus-store-preview-new-syntax#56]
In the process of using the plug-in, all the Chinese characters recorded in the database are garbled. I don't know where to modify them
I try to create a new table of utf8mb4 and UTF8, but they can't display Chinese correctly. This function is very important to me. I want to know whether the plug-in can't write Chinese?
This is used without making changes. The player's name is displayed in garbled code(The words in the red box should have been correct Chinese)：
![QQ截图20220416020502](https://user-images.githubusercontent.com/101586089/163605430-3fe48b6e-3824-4de5-bb9a-d21da92750d4.png)

This is displayed when I change the format in the table to GBK Chinese format(The words in the red box should have been correct Chinese):

![QQ截图20220416020450](https://user-images.githubusercontent.com/101586089/163605457-2e97e389-9c5b-4f1b-b71c-dfba172059b9.png)

This is very important to me and thank you very much for your contribution
In addition, I won't give up on the issues I raised about arm model errors and translation. I'm looking for time to improve

Thank you for your reply. You are the best plugin author I have met

**Comment by nuclearsilo583** [comment]
Please give me a little time.

**Comment by nuclearsilo583** [comment]
Hi, I have push a new fix for this issue. Please install and have some test. If you may find any bugs/error please keep comment here.

**Comment by Max66888** [comment]
After a simple test, the Chinese display is normal, and the problem has been solved. Thank you very much!
