### ISSUE TITLE
Trails won't work

### ISSUE THREAD

**Issue by Suddenx-Kemo** [nuclearsilo583/zephyrus-store-preview-new-syntax#57]
Grenade trails / player trails won't work if equipped, I checked config but nothing wrong, only working on preview.

**Comment by nuclearsilo583** [comment]
Which game you are using for those module

**Comment by Suddenx-Kemo** [comment]
Counter-Strike: Global Offensive with Sm 1.10

**Comment by nuclearsilo583** [comment]
First please check if your server/ your game dir have both .vmt and .vff file.

**Comment by Suddenx-Kemo** [comment]
Yes my server has both of them

**Comment by nuclearsilo583** [comment]
can you send me the item config in items.txt and the materials/texture of the trail

**Comment by Suddenx-Kemo** [comment]
It was fixed by reinstalling plugin, thanks you for replying me!
