### ISSUE TITLE
Native "FPVMI_SetClientModel" was not found

### ISSUE THREAD

**Issue by Suddenx-Kemo** [nuclearsilo583/zephyrus-store-preview-new-syntax#58]
So I just installed custom weapon skin module, and its not working so i typed "sm plugins info store_item_weaponmodel"
And i got this

  Filename: store_item_weaponmodel.smx
  Title: Store Custom Weapon Models (Custom Knife Models)
  Author: Mr.Derp & Franc1sco franug | Zephyrus Store Module & bbs.93x.net
  Version: 3.1
  URL: http://bbs.93x.net
  Error: Native "FPVMI_SetClientModel" was not found    <----------

**Comment by nuclearsilo583** [comment]
It requires [this](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/addons/sourcemod/scripting/fpvm_interface.sp) plugin to be able to use.

**Comment by Suddenx-Kemo** [comment]
Thank you for solving my problem!
