### ISSUE TITLE
Store

### ISSUE THREAD

**Issue by alfari24** [nuclearsilo583/zephyrus-store-preview-new-syntax#60]
sorry, where can i get the .smx file? I searched but couldn't find it so I can't running

**Comment by originalaidn** [comment]
Hi. You need to compile for yourself with SM compiler

**Comment by alfari24** [comment]
I get it, I'll try

**Comment by alfari24** [comment]
i have compiled, it's running.
but when I use the command !shop or /shop does not display the menu.

but when I try the command /shop aid or !shop aid = Item not found (plugins running just can't display the menu)

**Comment by originalaidn** [comment]
Did u added the config file? (sourcemod/configs/store/items.txt)

**Comment by alfari24** [comment]
I've added it, but it's not showing up

**Comment by originalaidn** [comment]
Can u paste errors?

And i edited now my last msg, u added the modules which u want to use?

**Comment by alfari24** [comment]
L 05/07/2022 - 16:01:54: [store.smx] Gifts! isn't installed or failed to load. Gifts support will be disabled. Please install Gifts. (http://forums.alliedmods.net/showthread.php?t=175185)
L 05/07/2022 - 16:02:31: [SM] Exception reported: File not found: addons\sourcemod\configs\readyup\readyup.cfg
L 05/07/2022 - 16:02:31: [SM] Blaming: readyup.smx
L 05/07/2022 - 16:02:31: [SM] Call stack trace:
L 05/07/2022 - 16:02:31: [SM]   [0] SetFailState
L 05/07/2022 - 16:02:31: [SM]   [1] Line 1262, F:\black_drive\rpg302\scripting\readyup.sp::OnConfigsExecuted
L 05/07/2022 - 16:02:31: [store.smx] SQL error happened.
Query: DELETE FROM store_logs WHERE `date` < (SELECT DATETIME('now', '-7 day'))
Error: no such table: store_logs

**Comment by originalaidn** [comment]
Firstly, did you restarted the server after added the store.smx?
And please check #41 and nuclearsilo's message.

**Comment by alfari24** [comment]
problem menu is complete. 

sorry before, is there a way to enter Name tag, name and message color. ? I don't see example in config/store/config_example

**Comment by originalaidn** [comment]
You need to add store_item_cpsupport, in the config same, in config examples : store_item_cpsupport.txt

**Comment by alfari24** [comment]
i got this
L 05/09/2022 - 02:40:33: [SM] Exception reported: Could not find file addons\sourcemod\configs\simple-chatcolors.cfg
L 05/09/2022 - 02:40:33: [SM] Blaming: simple-chatcolors.smx
L 05/09/2022 - 02:40:33: [SM] Call stack trace:
L 05/09/2022 - 02:40:33: [SM]   [0] SetFailState
L 05/09/2022 - 02:40:33: [SM]   [1] Line 1418, C:\compiler\simple-chatcolors.sp::ProcessConfigFile
L 05/09/2022 - 02:40:33: [SM]   [2] Line 1451, C:\compiler\simple-chatcolors.sp::ReloadConfigFiles
L 05/09/2022 - 02:40:33: [SM]   [3] Line 209, C:\compiler\simple-chatcolors.sp::OnPluginStart
L 05/09/2022 - 02:40:33: [SM] Unable to load plugin "simple-chatcolors.smx": Error detected in plugin startup (see error logs)

**Comment by originalaidn** [comment]
This is not a store module, you need chat-processor and the store_item_cpsupport

**Comment by alfari24** [comment]
oh i see 
014 "Basic Votes" (1.10.0.6537) by AlliedModders LLC
015 "Chat-Processor" (2.2.1) by Drixevel
016 "Client Preferences" (1.10.0.6537) by AlliedModders LLC

chat-processor and store_item_cpsupport running.
when I select Tag name, their Name color doesn't change, it's just that when I select preview they change, but chat remains normal without any changes

**Comment by originalaidn** [comment]
You have mysql connect?

**Comment by alfari24** [comment]
sm_store_database "store" like this ? but no table on mysql

**Comment by originalaidn** [comment]
Yes, this. Add in sourcemod/configs/database.cfg the store connect. After this restart your server and the plugin create tables.

**Comment by alfari24** [comment]
umm... I think it's the same as the previous problem, database connecting, plugin running, but no change in name color and name tag, only works in preview

**Comment by alfari24** [comment]
L 05/09/2022 - 03:59:08: [chat-processor.smx] Error parsing the flag message formatting config for game 'left4dead2', please verify its integrity.

**Comment by originalaidn** [comment]
You have left4dead2.ini in configs?

**Comment by originalaidn** [comment]
And in configs/chat_processor.cfg "left4dead2" ?
https://github.com/drixevel-dev/chat-processor/blob/main/configs/chat_processor.cfg

**Comment by originalaidn** [comment]
Can you send your L20220509.log and errors_20220509.log ?

**Comment by originalaidn** [comment]
Whats the store-chat.smx?
And u writed !tgs ?

If not work, maybe good if you sent your plugins list..

**Comment by alfari24** [comment]
] sm plugins list
[SM] Listing 107 plugins:
  001 "ABM" (0.1.95) by Victor "NgBUCKWANGS" Gonzalez
  002 "Automatic Campaign Switcher (ACS)" (v2.3.0) by Rikka0w0, Chris Pringle
  003 "Admin File Reader" (1.10.0.6537) by AlliedModders LLC
  004 "Admin Help" (1.10.0.6537) by AlliedModders LLC
  005 "Admin Menu" (1.10.0.6537) by AlliedModders LLC
  006 "Advertisements" (2.1.1) by Tsunami
  007 "L4D2 Ghost-Cheat Preventer" (1.0) by Sir
  008 "[L4D2] Usercommands Check" by BHaType
  009 "Basic Ban Commands" (1.10.0.6537) by AlliedModders LLC
  010 "Basic Chat" (1.10.0.6537) by AlliedModders LLC
  011 "Basic Comm Control" (1.10.0.6537) by AlliedModders LLC
  012 "Basic Commands" (1.10.0.6537) by AlliedModders LLC
  013 "Basic Info Triggers" (1.10.0.6537) by AlliedModders LLC
  014 "Basic Votes" (1.10.0.6537) by AlliedModders LLC
  015 "Chat-Processor" (2.2.1) by Drixevel
  016 "Client Preferences" (1.10.0.6537) by AlliedModders LLC
  017 "Discord API" (0.1.103) by Deathknife
  018 "Fast Healing" (1.0) by WhatsAnName
  019 "Fix frozen tanks" (2.0) by sheo
  020 "Fun Commands" (1.10.0.6537) by AlliedModders LLC
  021 "Fun Votes" (1.10.0.6537) by AlliedModders LLC
  022 "Infra's Simple Discord Chat Relay" (1.0.0) by Infra
  023 "[L4D2] HP Regeneration" (1.63) by Mortiegama
  024 "[L4D2] Witch Precache" (1.0) by CanadaRox
  025 "[L4D2] F-18 Airstrike" (1.8) by SilverShot
  026 "[L4D2] F-18 Airstrike - Dead Air" (1.3-da) by SilverShot
  027 "[L4D2] F-18 Airstrike - No Mercy" (1.3-nm) by SilverShot
  028 "[L4D2] F-18 Airstrike - Triggers" (1.3-tr) by SilverShot
  029 "l4d2_changelevel" (1.2.0) by Lux
  030 "[L4D2] Footlocker" (1.17) by SilverShot
  031 "[L4D] DragoStats" (1.0.30) by Dragokas & MAKS
  032 "[L4D2] Incapped Crawling with Animation" (2.8) by SilverShot, mod by Lux
  033 "[L4D2] Campaign/Map Voter" (0.666 beta) by satannuts
  034 "L4D2 Menu" by pan0s
  035 "L4D2 Mission Manager" (v1.0.0) by Rikka0w0
  036 "L4D2 MissionManager AdminMenu" (v1.0.0) by Rikka0w0
  037 "[L4D2] Tank health gauge" (1.2) by ztar
  038 "L4D2 Tank Announcer" (1.0) by Visor
  039 "[L4D2] Weapon/Zombie Spawner" (1.0a) by Zuko & McFlurry
  040 "L4D2_WorldModel_Turnrate" (1.0) by Lux
  041 "[L4D/L4D2] Infected Bots (Coop/Versus/Realism/Scavenge/Survival)" (2.6.8) by djromero (SkyDavid), MI 5, Harry Potter
  042 "[L4D & L4D2] Achievement Trophy" (2.5) by SilverShot
  043 "[L4D & L4D2] Health Cabinet" (1.12) by SilverShot
  044 "L4D_Cloud_Damage" (2.22) by  AtomicStryker
  045 "l4d_death_toll_train_bridge_event_v0.0.1.smx"
  046 "L4D - Death Toll tunnel block crescendo" (0.0.1) by finishlast
  047 "[L4D & L4D2] Extinguisher and Flamethrower" (1.19) by SilverShot
  048 "l4d_garage01_alleys_pimp.smx"
  049 "[L4D1 & L4D2] Gascan Invulnerable" (1.0.8) by Mart
  050 "[L4D & L4D2] Gun Cabinet" (1.3) by SilverShot
  051 "L4D1 l4d_hospital03_sewers_pimp" (1.0) by finishlast
  052 "l4d_hospital03_sewers_pimp2.smx"
  053 "[L4D & L4D2] Mission and Weapons - Info Editor" (1.12) by SilverShot
  054 "[L4D & L4D2] Lift Music" (1.5) by SilverShot
  055 "Machine" (1.07) by Pan Xiaohai
  056 "Multiple Equipment" (3.6) by MasterMind420 & Ludastar & Pan Xiaohai & Marcus101RR
  057 "L4D - No Mercy car barricade crescendo" (0.0.1) by finishlast
  058 "[L4D & L4D2] Reload Fix - Max Clip Size" (1.3a) by SilverShot
  059 "l4d_river01_docks_pimp2.smx"
  060 "L4D - Sacrifice boat crescendo" (0.0.1) by finishlast
  061 "l4d_river02_barge_house_explode.smx"
  062 "[L4D & L4D2] Saferoom Door Spam Protection" (1.18) by SilverShot
  063 "l4d_smalltown01_caves_pimp.smx"
  064 "l4d_smalltown01_caves_tank_explode.smx"
  065 "l4d_smalltown03_ranchhouse_plane_fire.smx"
  066 "L4D SM Respawn" (1.9.3) by AtomicStryker & Ivailosp
  067 "[L4D & L4D2] Weapon Crate" (1.5) by SilverShot
  068 "LagFixer" (1.0) by tRololo312312
  069 "[L4D & L4D2] Left 4 DHooks Direct" (1.100) by SilverShot
  070 "Player Commands" (1.10.0.6537) by AlliedModders LLC
  071 "[L4D2] Poof" (1.35) by blackalegator
  072 "Quick Revive Dur only" (1.0) by WhatsAnName
  073 "Quick Revive" (1.0) by WhatsAnName
  074 "RemoveFF" by Lux
  075 "Reserved Slots" (1.11.0.6625) by AlliedModders LLC
  076 "SaveChat" (SaveChat_1.5) by citkabuto & Harry Potter
  077 "Sound Commands" (1.10.0.6537) by AlliedModders LLC
  078 "Source Chat Relay" (v2.1.5-2-gd81f03c) by Fishy
  079 "Store - Trade System" (2.0) by Zephyrus, nuclear silo
  080 "Store - The Resurrection with preview rewritten compilable with SM 1.10 new syntax" (6.7) by Zephyrus, nuclear silo, AiDN™
  081 "Blackjack" (1.4) by HerrMagic and Originalz ft. Jannik, AiDN™, nuclear silo
  082 "Store - Coinflip gamble module" (1.4) by shanapu, nuclear silo
  083 "Store - Crowns gamble module" (1.5) by shanapu, nuclear silo, AiDN™
  084 "Store - Dice gamble module" (1.4) by shanapu, nuclear silo
  085 "High or Low" (1.1) by SheriF & AiDN™
  086 "Store - Jackpot gamble module" (1.4) by shanapu, nuclear silo, AiDN™
  087 "Store - Roulette gamble module" (1.5) by shanapu, nuclear silo
  088 "Store - Admin / Vip Flags Fore Store" (1.0) by nuclear silo
  089 "Store - Bulletsparks item module" (1.2) by shanapu, nuclear silo
  090 "Store - Chat Processor item module with Scoreboard Tag" (2.2) by nuclear silo, Mesharsky, AiDN™
  091 "Store Grenade Trail" (1.0) by zephyrus, nuclear silo
  092 "Store - Hats Module" (1.2) by nuclear silo
  093 "Store - Hats Module [No ThirdPerson Plugin]" (1.2) by nuclear silo
  094 "Store - Info panel item module" (1.1) by shanapu, nuclear silo
  095 "Store - Laser sight item module" (1.1) by zephyrus, nuclear silo
  096 "Store - Link item module" (1.0) by shanapu, nuclear silo
  097 "Store - Particle item module" (1.3) by shanapu, nuclear silo
  098 "Store - Tracers Module" (1.1) by nuclear silo
  099 "Store - Dosh money module" (1.1) by shanapu, AiDN™
  100 "Store Giveaway" (1.4) by nuclear silo
  101 "Store Giveaway AiDN™ version" (1.0) by nuclear silo, AiDN™
  102 "Math Quiz" (1.2) by Arkarr & Simon & AiDN™
  103 "Store - Voucher module" (1.7) by shanapu, nuclear silo
  104 "Thirdperson Mode" (1.0) by Zephyrus
  105 "Vote Blocker" (1.3.4) by Phil Bradley
  106 "PlayerJoin" (1.0) by WinCher
  107 "[L4D2]sv_steamgroupfixer.smx"

**Comment by originalaidn** [comment]
Thanks, this is not part of the problem, but only use one module from giveaway and hats.

But I don't know what cause this problem, maybe @nuclearsilo583 can help you.

**Comment by alfari24** [comment]
ok, thanks

can i ask something ? i try to use pet on l4d2 use haipa_v2.mdl but getting error while preview or equip , how solution ?

**Comment by nuclearsilo583** [comment]
You can check the materials error in #21
