### ISSUE TITLE
Can I use MySQL? Just like the original

### ISSUE THREAD

**Issue by GhostZhr1998** [nuclearsilo583/zephyrus-store-preview-new-syntax#61]

**Comment by originalaidn** [comment]
Yes of course, u can use mysql. Need to set the mysql in cfg/sourcemod/plugin.store.cfg : sm_store_database

**Comment by GhostZhr1998** [comment]
I am a novice, how to compile SMX？

> 是的，当然，你可以使用 mysql。需要在 cfg/sourcemod/plugin.store.cfg 中设置 mysql : sm_store_database

I am a novice, how to compile SMX？

**Comment by originalaidn** [comment]
You need to download from sourcemod.net the stable or dev builds. And download the OS u use (I think u use Windows), which is not red.

When u download, only need the scripting folder, add to this folder the store's .sp-s and start the spcomp

**Comment by GhostZhr1998** [comment]
> You need to download from sourcemod.net the stable or dev builds. And download the OS u use (I think u use Windows), which is not red.
> 
> When u download, only need the scripting folder, add to this folder the store's .sp-s and start the spcomp.exe
> 
> When no errors, you get a compiled folder in the scripting. Move these files to ur server's plugins folder
i can not find the store's .sp-s,where is it?

**Comment by originalaidn** [comment]
Download the github, and the store's sp-s in addons/sourcemod/scripting
Need all folders (include, store) and the files

**Comment by GhostZhr1998** [comment]
> 下载github，和store的sp-s在addons/sourcemod/scripting 需要所有文件夹（include，store）和文件

Thank you very much. I got it. I'll go to my server experiment
![image](https://user-images.githubusercontent.com/67358635/167384698-4cf3ba17-005e-4282-a1fc-eeb135a162e3.png)

**Comment by GhostZhr1998** [comment]
> 

What files should I upload to my server to open the store?
eg:  store.smx
configs(store)

**Comment by GhostZhr1998** [comment]
> 是的，你需要 store.smx，如果你想下载模块，需要编译它。如果添加 store.smx 或其他模块，需要重启服务器。

Can I just replace the original store.smx?

**Comment by originalaidn** [comment]
Yes, you can. But for safe first download the previous version.
If you want only to get credits, enough if u add store.smx but u can add modules (trails, hats, tracers, saysounds, nametags)
