### ISSUE TITLE
how to use module Trails for Left 4 dead 2 ? 

### ISSUE THREAD

**Issue by alfari24** [nuclearsilo583/zephyrus-store-preview-new-syntax#63]
because i think that plugins support only for CSGO

plugins can't run

**Comment by alfari24** [comment]
I tried to install the skin plugins player but it seems the legs and arms are still, and when it walks like a moving statue, is there a solution?

**Comment by nuclearsilo583** [comment]
1. The trail works for l4d2. You can remove [this](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/addons/sourcemod/scripting/store_item_trails.sp#L7) line and recompile. It should work since that line need cstrike extension to run but we dont need it.
2. Did you ise the player skin module from l4d2 folder? If so could you give me some screenshot.

**Comment by alfari24** [comment]
![image](https://user-images.githubusercontent.com/56450870/168494521-913de4b8-b975-4c10-aedf-82728401863b.png)
trails plugins running thanks sir.

skin and pet players, when they walk there is no movement of the hands and feet, like a moving statue

**Comment by alfari24** [comment]
![image](https://user-images.githubusercontent.com/56450870/168529379-6e7123f9-0137-4099-822a-e6d4e11a36f6.png)
like this right ?

**Comment by nuclearsilo583** [comment]
Maybe the model didnt compile for l4d2. You can decompile the model and compile it with l4d2 engine. is this a pet or player skin model.

**Comment by alfari24** [comment]
this skin for model. 
in this picture the skin can enter and be used in the game, it's just that the hands and feet can't be moved. when tried in model viewer error Version differs: expected "10", got "49"
![image](https://user-images.githubusercontent.com/56450870/168533837-86a149f0-0a13-4b7c-b037-425cb13675ab.png)


![image](https://user-images.githubusercontent.com/56450870/168533960-b6f117de-4e07-453c-bfef-b4e8a0cb7c9f.png)
but this model in the model viewer can be loaded, but when in the game it crashes

I will try to decompile
