### ISSUE TITLE
[Particles] sm_settings ON/OFF switches are inverted

### ISSUE THREAD

**Issue by azalty** [nuclearsilo583/zephyrus-store-preview-new-syntax#64]
When "Disabled" is showed, particles are enabled, and when "Enabled" is showed, particles are disabled

![image](https://user-images.githubusercontent.com/36737524/168820720-08a5708f-f23d-4026-b781-e0bc029ac7e9.png)
![image](https://user-images.githubusercontent.com/36737524/168820797-060bf89f-4cf8-4ca4-b8ac-7865350a6d5a.png)

There is also a small translations error (Particless)

This applies for the Particles module, but could happen for other ones as well

**Comment by originalaidn** [comment]
Only the chat isn't working properly, the menu is perfect (as shown in the pictures).
I don't think "particless" is a translation error, the + s is in "item visible".

**Comment by originalaidn** [comment]
in my PR edited some chat problem, the "Particless are visible again" and menu still, only the "Particless are visible again" not too good.

When "Hide Shop Particle: Enabled", you hided the particles.

**Comment by originalaidn** [comment]
removed #62 from pr, now this edit in #72 with edited menu

**Comment by azalty** [comment]
Fixed by #72
