### ISSUE TITLE
Can't see trails on l4d2

### ISSUE THREAD

**Issue by alfari24** [nuclearsilo583/zephyrus-store-preview-new-syntax#65]
I have a little problem with trails. 
1. trails can only be seen when changing maps. 
2. but when continuing chapter trails can't be seen .

Note : if granad trails there is no problem

**Comment by originalaidn** [comment]
When you start the server, you connect and didn't see the trails, need to download S Downloader (https://forums.alliedmods.net/showthread.php?t=269792) or any downloader, precacher plugin

**Comment by alfari24** [comment]
when I join the trail sometimes it can be seen immediately and sometimes not. and every time I change maps the trails can be seen on some players but it's random, sometimes it's acceptable and sometimes it's not when I change maps, I use pugins precacher and fast dl.

S-dowloader plugins make crash

**Comment by alfari24** [comment]
this log error file https://mega.nz/file/2MY2AYoa#uUnE9lphau4WsR1eY148zqjokuLrgEFhSiHNTQZiS3s

**Comment by alfari24** [comment]
maybe this video can help to explain what happened.

https://mega.nz/file/nBJAmJ5Q#_EdCde1faG5MUdEa-e3rXGTxJSGAuH8cpFxwQQDc1yw

**Comment by alfari24** [comment]
https://imgur.com/a/ujkUsWs

I still can't solve this trails problem, are these cookies the cause?

**Comment by azalty** [comment]
> https://imgur.com/a/ujkUsWs
> 
> 
> 
> I still can't solve this trails problem, are these cookies the cause?

Do /settings and try showing and hiding trails to try to refresh them

I don't use trails personally so I can't really help
