### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by eternity19** [nuclearsilo583/zephyrus-store-preview-new-syntax#7]
Hello can you made store_item_bullet_impact and grentrails to work? And can you tell me how to config store_item_bulletsparks and store_item_trails? Thanks

**Comment by nuclearsilo583** [comment]
For grenadetrail please comment this [line](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/scripting/store.sp#L2) and uncomment this [line](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/scripting/store.sp#L169) in store.sp then recompile the plugin. This will re-enable grenadetrail plugins. I will update it as seperated standalone plugin soon. 
For bullet_impact. Do you have error on running the plugins or you need an example of config.
For those go [here](https://pastebin.com/jzqJhHDy)

**Comment by eternity19** [comment]
Thanks for your answer. But i want grenadetrail with #pragma newdecls maybe you will do it soon. I dont know for bullet_impact i don`t see paintballs on the wall.

**Comment by nuclearsilo583** [comment]
oh sure, i will update it at weekend

**Comment by eternity19** [comment]
Can you tell me how to fix this?
L 05/05/2021 - 10:21:33: [SM] Exception reported: Invalid timer handle 9fa00b5d (error 3)
L 05/05/2021 - 10:21:33: [SM] Blaming: store.smx
L 05/05/2021 - 10:21:33: [SM] Call stack trace:
L 05/05/2021 - 10:21:33: [SM]   [0] KillTimer
L 05/05/2021 - 10:21:33: [SM]   [1] Line 486, E:\sourcemod compile\sourcemod\scripting\include\zephstocks.inc::ClearTimer
L 05/05/2021 - 10:21:33: [SM]   [2] Line 3268, store.sp::Store_DisconnectClient
L 05/05/2021 - 10:21:33: [SM]   [3] Line 1174, store.sp::OnClientDisconnect

**Comment by eternity19** [comment]
Maybe, delete the timer?

**Comment by nuclearsilo583** [comment]
This occur when player connect and disconnect before he is actually in the server (disconnect while in loading screen).
No need to worry about this

**Comment by eternity19** [comment]
The store command is broken now https://www.dropbox.com/s/9e2bs18c1r6h13i/20210510193651_1.jpg?dl=0

**Comment by nuclearsilo583** [comment]
Can you give me error log

**Comment by nuclearsilo583** [comment]
You are missing translation. Please update new translation on master. 
Yes i will

**Comment by eternity19** [comment]
I still dont see paintball. For me dosnt work.

**Comment by nuclearsilo583** [comment]
After the server restart. You need to reload the map. Change map 2nd time you will see paintball since csgo update broke many things

**Comment by eternity19** [comment]
Sprays has same problem with valve update?

**Comment by nuclearsilo583** [comment]
spray use custom materials. Not the valve's sprays

**Comment by eternity19** [comment]
Yes i use custom but i have same problem i don`t see them on the wall. If i use preview option i see them.

**Comment by nuclearsilo583** [comment]
Stay close to the wall then press E. If you dont see it. Try to spray on another wall's materials. Some wall cant be seen cause for it's texture

**Comment by eternity19** [comment]
Where I found weapons skin plugin and skins for them?

**Comment by nuclearsilo583** [comment]
Custom weapon model or valve's skin. There are many plugin you can find online. Just search in google. if you are too lazy to find by yourself.
Here the valve skin [plugin]( https://forums.alliedmods.net/showthread.php?t=298770)
Model go [gamebanana](https://gamebanana.com/mods/cats/7370)

**Comment by eternity19** [comment]
No this what you use for store https://youtu.be/TT7CwhIIPEc

**Comment by nuclearsilo583** [comment]
You can find those [here](https://gamebanana.com/mods/cats/7420)

**Comment by eternity19** [comment]
and plugin?

**Comment by nuclearsilo583** [comment]
You need this [plugin](https://forums.alliedmods.net/showthread.php?t=276697) to work.

**Comment by eternity19** [comment]
thanks
