### ISSUE TITLE
Where can I find a compiled version of this plugin?

### ISSUE THREAD

**Issue by INewWorldI** [nuclearsilo583/zephyrus-store-preview-new-syntax#71]
Compilation errors occur in the latest version 1.10. and 1.11 of the source mode.

I want to use this well-made plugin...

1.11 Compiled 
//SourceMod Batch Compiler
// by the SourceMod Dev Team

//// store.sp
//
// C:\Users\kk971\Downloads\sourcemod-1.11.0-git6888-linux\addons\sourcemod\scripting\include\admin.inc(201) : error 017: undefined symbol "FlagBitsToArray"
// C:\Users\kk971\Downloads\sourcemod-1.11.0-git6888-linux\addons\sourcemod\scripting\include\admin.inc(201) : warning 215: expression has no effect
// C:\Users\kk971\Downloads\sourcemod-1.11.0-git6888-linux\addons\sourcemod\scripting\include\admin.inc(201) : warning 215: expression has no effect
// C:\Users\kk971\Downloads\sourcemod-1.11.0-git6888-linux\addons\sourcemod\scripting\include\admin.inc(201) : warning 215: expression has no effect
// C:\Users\kk971\Downloads\sourcemod-1.11.0-git6888-linux\addons\sourcemod\scripting\include\admin.inc(201) : error 001: expected token: ";", but found ")"
// C:\Users\kk971\Downloads\sourcemod-1.11.0-git6888-linux\addons\sourcemod\scripting\include\admin.inc(201) : error 029: invalid expression, assumed zero
// C:\Users\kk971\Downloads\sourcemod-1.11.0-git6888-linux\addons\sourcemod\scripting\include\admin.inc(201) : fatal error 190: too many error messages on one line
//
// Compilation aborted.
// 4 Errors.
//
// Compilation Time: 0.47 sec

//SourceMod Batch Compiler
// by the SourceMod Dev Team

1.10 Compiled 
//// store.sp
//
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(20) : error 001: expected token: "{", but found "struct"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(22) : error 001: expected token: "public", but found "char"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(23) : error 001: expected token: "}", but found "int"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(25) : error 054: unmatched closing brace ("}")
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(27) : error 001: expected token: "{", but found "struct"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(29) : error 001: expected token: "public", but found "char"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(30) : error 001: expected token: "}", but found "char"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(46) : error 054: unmatched closing brace ("}")
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(48) : error 001: expected token: "{", but found "struct"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(50) : error 001: expected token: "public", but found "char"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(51) : error 001: expected token: "}", but found "char"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(60) : error 054: unmatched closing brace ("}")
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(62) : error 001: expected token: "{", but found "struct"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(64) : error 001: expected token: "public", but found "int"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(65) : error 001: expected token: "}", but found "int"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(71) : error 054: unmatched closing brace ("}")
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(87) : error 017: undefined symbol "Store_Item"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(87) : error 001: expected token: ";", but found "]"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(88) : error 017: undefined symbol "Type_Handler"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(88) : error 001: expected token: ";", but found "]"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(91) : error 017: undefined symbol "Client_Item"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\store.inc(91) : error 001: expected token: ";", but found "]"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\zephstocks.inc(38) : error 001: expected token: "{", but found "struct"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\zephstocks.inc(45) : error 054: unmatched closing brace ("}")
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\zephstocks.inc(107) : error 017: undefined symbol "g_eCvars"
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\zephstocks.inc(107) : warning 215: expression has no effect
// C:\Users\kk971\Downloads\sourcemod-1.10.0-git6542-linux\addons\sourcemod\scripting\include\zephstocks.inc(107) : error 001: expected token: ";", but found "]"
//
// Compilation aborted.
// 26 Errors.
//
// Compilation Time: 0.59 sec
// ----------------------------------------

Press enter to exit ...

**Comment by nuclearsilo583** [comment]
make sure you have replace all the file in 2 folder (include and store) in github scripting folder to your scripting folder

**Comment by INewWorldI** [comment]
I put all the folders on github into my folder and compiled it. You guys tried, but the problem occurred

**Comment by nuclearsilo583** [comment]
I compile in window version of sourcemod and I can compile it normally.

**Comment by INewWorldI** [comment]
Shouldn't the Linux version of the compiler work? Oh... i try Is there any problem with operation?

**Comment by nuclearsilo583** [comment]
maybe the OS problem. Try to compile it on windows OS and move the .smx to your server

**Comment by INewWorldI** [comment]
Ok, it compiles fine, but I have a question about the player skin issue. Can't use player skins? Is it correct that the menu should be displayed even if there is no skin in the item.cfg provided by default?

**Comment by nuclearsilo583** [comment]
No. You need to have the model file in your server folder to get the item displayed in the menu.

**Comment by INewWorldI** [comment]
oh thanks for the help it works

**Comment by INewWorldI** [comment]
I would be grateful if any additional questions could be answered.

What is the function of that image?
It doesn't seem like a server error, and I suspect that something similar is refreshing the toplist.

I wonder how to solve it
Thanks for the good plugin.

**Comment by INewWorldI** [comment]
Ah mistak
![Screenshot_1](https://user-images.githubusercontent.com/32818386/174069937-179de844-6dcb-4a6e-a56b-1b25b590503a.png)
e

**Comment by originalaidn** [comment]
cfg/sourcemod/store/crash.cfg set store_crash_notify_player "1" to "0"

**Comment by INewWorldI** [comment]
Solved Thanks, 
but I wonder what store_gamble_crash.smx does.

**Comment by originalaidn** [comment]
Thats a gambling module, u can check the info in !crash - Info panel
