### ISSUE TITLE
I have a question about player skins and translation files.

### ISSUE THREAD

**Issue by INewWorldI** [nuclearsilo583/zephyrus-store-preview-new-syntax#78]
![KakaoTalk_20220617_093211544](https://user-images.githubusercontent.com/32818386/175878888-e667f3f8-895a-4e90-a5c2-45dbfb49ebbf.png)
![KakaoTalk_20220617_093211907](https://user-images.githubusercontent.com/32818386/175878893-fe0d67cb-202a-424b-9bb0-a1cf74f9848b.png)

In the case of the skin with the body and arm in one model file, it seemed that it could not be used in the store.

Is it possible to use it by using a specific function?

The two files must be loaded together to become a complete skin.

Once I found the normal model file and solved it.

Can I use a language other than English for translation files?

It may be my mistake that I can't load the translation file, but I'd like to ask a question.

**Comment by nuclearsilo583** [comment]
1. The plugin itself already support for that try to use these 2 configs string
![image](https://user-images.githubusercontent.com/58926275/175918724-2e2011a2-3038-4475-a8bc-1941b53cb216.png)
2. You can change anything in the translations file for your server usage. It's totally in your control.

**Comment by INewWorldI** [comment]
You have sent a friend request.
