### ISSUE TITLE
CPsupport not use nickname color

### ISSUE THREAD

**Issue by INewWorldI** [nuclearsilo583/zephyrus-store-preview-new-syntax#79]
![Screenshot_1](https://user-images.githubusercontent.com/32818386/177601449-a376b176-3d9b-40f0-9df0-41c6c0267d5c.png)

I checked and applied yesterday's update, and the same result occurred. Report bugs.

**Comment by INewWorldI** [comment]
And I wonder about the application to ZRCLASS in the store

I defined a special class in playerclass and put the name value of that class in the store

I was wondering if that class could only be used as a store purchase. Should I define it as a group?

Maybe I have the settings wrong.,

**Comment by nuclearsilo583** [comment]
1. Is that message was from say_team
2. First you should put this cvar zr_classes_default_zombie to "" in the cfg file and in the playerclasses.txt just create a new class with the same attribute and leave "enable" and "team_default" to 0
![image](https://user-images.githubusercontent.com/58926275/177606741-99b6c2bd-b8d8-41ce-9f8e-26736c2417bb.png)

**Comment by nuclearsilo583** [comment]
what version of chat-processor you're using.
