### ISSUE TITLE
Problem with compiling

### ISSUE THREAD

**Issue by Gamerrr** [nuclearsilo583/zephyrus-store-preview-new-syntax#8]
Hi, i have problem with compiling plug. Can you fix it?
it is problem with **store-trade** one first line
others only have errors
![1](https://user-images.githubusercontent.com/40613577/116942434-dd5be080-ac71-11eb-8751-18e81f010dfc.PNG)
![2](https://user-images.githubusercontent.com/40613577/116942439-df25a400-ac71-11eb-88c3-c829b2260c94.PNG)

**Comment by nuclearsilo583** [comment]
You are using wrong zephstocks.inc 
Please use the latest inc on master
