### ISSUE TITLE
"sm_givecredits @all" kicks client because of too many commands executed

### ISSUE THREAD

**Issue by Bernardino18** [nuclearsilo583/zephyrus-store-preview-new-syntax#82]
How to reproduce:
- Have ~ 40 players online in server
- Execute sm_givecredits @\all"
- Got kicked

https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/addons/sourcemod/scripting/store.sp#L1938

**Comment by azalty** [comment]
`@all` and other selectors are poorly handled too

Thanks for reporting

**Comment by nuclearsilo583** [comment]
this will be fix in the next store core commit. Please wait.
