### ISSUE TITLE
Not enough space on the stack

### ISSUE THREAD

**Issue by INewWorldI** [nuclearsilo583/zephyrus-store-preview-new-syntax#83]
Is this a server issue?

`L 07/10/2022 - 10:31:36: [SM] Exception reported: Not enough space on the stack
L 07/10/2022 - 10:31:36: [SM] Blaming: store_item_pet.smx
L 07/10/2022 - 10:31:36: [SM] Call stack trace:
L 07/10/2022 - 10:31:36: [SM]   [1] Line 656, C:\Users\kk971\Downloads\sourcemod-1.11.0-git6905-linux\addons\sourcemod\scripting\store_item_pet.sp::Downloader_AddFileToDownloadsTable
L 07/10/2022 - 10:31:36: [SM]   [2] Line 695, C:\Users\kk971\Downloads\sourcemod-1.11.0-git6905-linux\addons\sourcemod\scripting\include\zephstocks.inc::Downloader_AddFileToDownloadsTable
L 07/10/2022 - 10:31:36: [SM]   [3] Line 681, C:\Users\kk971\Downloads\sourcemod-1.11.0-git6905-linux\addons\sourcemod\scripting\include\zephstocks.inc::Downloader_AddFileToDownloadsTable
L 07/10/2022 - 10:31:36: [SM]   [4] Line 134, C:\Users\kk971\Downloads\sourcemod-1.11.0-git6905-linux\addons\sourcemod\scripting\store_item_pet.sp::Pets_OnMapStart
L 07/10/2022 - 10:31:36: [SM]   [6] Call_Finish
L 07/10/2022 - 10:31:36: [SM]   [7] Line 784, C:\Users\kk971\Downloads\sourcemod-1.11.0-git6905-linux\addons\sourcemod\scripting\store.sp::OnMapStart
`

**Comment by azalty** [comment]
Seems like a memory leak caused by `store_item_pet` and the `Downloader_AddFileToDownloadsTable` function

Maybe you have invalid models

**Comment by INewWorldI** [comment]
This is a relatively recent version. Last time I left a problem with Rainbow cp issue. It's probably a file before the lootbox patch.

**Comment by nuclearsilo583** [comment]
The problem occur with the stable SM 1.11 and the Downloader_AddFileToDownloadsTable table. I recommend you to remove all the code from [131-135](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/addons/sourcemod/scripting/store_item_pet.sp#L131-#L135) and install one of [these](https://forums.alliedmods.net/showthread.php?p=602270) [plugin](https://forums.alliedmods.net/showthread.php?t=269792) for precache model.

**Comment by INewWorldI** [comment]
ok thx
