### ISSUE TITLE
Too many connections lagging MySQL Server

### ISSUE THREAD

**Issue by Bernardino18** [nuclearsilo583/zephyrus-store-preview-new-syntax#86]
This is the processlist showing the connections on my MySQL server.
Showing in total 78 connections on this plugin.
Compared to sourcebans that has only 16 connections.

Sourcebans and Store are on the same game servers.

![image](https://user-images.githubusercontent.com/44657114/179573436-74744311-03ac-4987-a418-4674beba4b5b.png)
![image](https://user-images.githubusercontent.com/44657114/179573557-6838c2a9-e6eb-4899-9554-98bf1a407bf5.png)

**Comment by nuclearsilo583** [comment]
Try change sv_hibernate_when_empty to 0.

**Comment by Bernardino18** [comment]
Lower the connections but still high compared to sourcebans.
Also disabled [this cvar](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/cfg/sourcemod/plugin.store.cfg#L190) and restarted all game servers

![image](https://user-images.githubusercontent.com/44657114/180574558-bc056547-0257-4176-b436-30f6907a9c33.png)

I noticed store and submodules have three connections associated to same database

![image](https://user-images.githubusercontent.com/44657114/180574238-6f39ba7a-a901-4953-8292-5b90eaebc17d.png)

**Comment by nuclearsilo583** [comment]
Tr disable one or both of submodules to see how many connection will it reduce.

**Comment by Bernardino18** [comment]
Disabling voucher submodule reduce connections, but still high compared to sourcebans plugin.
Conclusion: The submodules should be using the same sql connection from main plugin.

**Comment by azalty** [comment]
Thanks for reporting.

The main reason is probably that it connects to the database on `OnConfigExecuted` which is called once per map change, and doesn't check if we're already connected to the db, and just creates a new connection. [Here's an example of this problem in the `store_item_cpsupport.sp` file](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/addons/sourcemod/scripting/store_item_cpsupport.sp#L225)
