### ISSUE TITLE
Not enough space on the stack on custom weapons

### ISSUE THREAD

**Issue by INewWorldI** [nuclearsilo583/zephyrus-store-preview-new-syntax#87]
error logs link https://pastebin.com/rsHCU51L

L 07/17/2022 - 14:42:57: [SM] Exception reported: Not enough space on the stack
L 07/17/2022 - 14:42:57: [SM] Blaming: store_item_grenskins.smx
L 07/17/2022 - 14:42:57: [SM] Call stack trace:
L 07/17/2022 - 14:42:57: [SM]   [1] Line 276, C:\Users\kk971\Desktop\Server\sourcemod-1.11.0-git6905-linux\addons\sourcemod\scripting\store_item_grenskins.sp::Downloader_AddFileToDownloadsTable
L 07/17/2022 - 14:42:57: [SM]   [2] Line 695, C:\Users\kk971\Desktop\Server\sourcemod-1.11.0-git6905-linux\addons\sourcemod\scripting\include\zephstocks.inc::Downloader_AddFileToDownloadsTable
L 07/17/2022 - 14:42:57: [SM]   [3] Line 681, C:\Users\kk971\Desktop\Server\sourcemod-1.11.0-git6905-linux\addons\sourcemod\scripting\include\zephstocks.inc::Downloader_AddFileToDownloadsTable
L 07/17/2022 - 14:42:57: [SM]   [4] Line 79, C:\Users\kk971\Desktop\Server\sourcemod-1.11.0-git6905-linux\addons\sourcemod\scripting\store_item_grenskins.sp::GrenadeSkins_OnMapStart
L 07/17/2022 - 14:42:57: [SM]   [6] Call_Finish
L 07/17/2022 - 14:42:57: [SM]   [7] Line 785, C:\Users\kk971\Desktop\Server\sourcemod-1.11.0-git6905-linux\addons\sourcemod\scripting\store.sp::OnMapStart

I'm trying to put a custom sword skin, but I'm having trouble.

Does it have anything to do with that error log?

If you restart after setting it in the item cfg, it will be displayed normally in the shop menu, and one of the sword skins will be worn normally, but the other skins will not be applied.

I tested it with other plugins and it works fine.

**Comment by azalty** [comment]
Got this error as well, occurs when you start your server for the first time, models aren't precached properly and will crash your server is used the first map.

Fixed on my side by reloading the map the first time a player spawns. A proper fix, if possible, would be welcome though.

**Comment by azalty** [comment]
Check #83

**Comment by INewWorldI** [comment]
You are already using an external plugin.
I already know about the linked answer.

The linked one is a pet, this is a custom weapon.

First, the developers patched it last time and are reporting the same issue. I'll take action first. Thank you.

**Comment by azalty** [comment]
Oh yea you created the other issue too 😵

**Comment by INewWorldI** [comment]
Yes, I think the developer would probably fix it in the same way if the circumstances were right.
