### ISSUE TITLE
Anyone can use the givecredit command

### ISSUE THREAD

**Issue by ardahzr** [nuclearsilo583/zephyrus-store-preview-new-syntax#9]
Hi, I'm not sure if I'm missing something. Everyone can use the givecredit command in the game. If this is a bug, can you fix it?

**Comment by nuclearsilo583** [comment]
Please check this [cvar](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/cfg/sourcemod/plugin.store.cfg#L8)
