### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WizardJailbreak** [nuclearsilo583/zephyrus-store-preview-new-syntax#95]
Hi
Anybody can help me?
The plugin is write this in console:
[-N- Arms Fix] Nothing changed, config is ready.
[AbNeR RES] SOUNDS: 10 sounds loaded from "sound/misc/tecnohard"
Unknown command "weapons"
L 08/06/2022 - 19:30:50: [store_jb.smx] Init CP...
L 08/06/2022 - 19:30:50: [sm_ctban.smx] Default database database connection failure: [2002]: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
L 08/06/2022 - 19:30:50: [SM] Exception reported: Error while connecting to default database. Exiting.
L 08/06/2022 - 19:30:50: [SM] Blaming: sm_ctban.smx
L 08/06/2022 - 19:30:50: [SM] Call stack trace:
L 08/06/2022 - 19:30:50: [SM]   [0] SetFailState
L 08/06/2022 - 19:30:50: [SM]   [1] Line 1638, D:\Perso\expbox\addons\sourcemod\scripting\sm_ctban.sp::DB_Callback_Connect
L 08/06/2022 - 19:30:50: [SM] Exception reported: Can not retrieve item.parent from database: no result row
L 08/06/2022 - 19:30:50: [SM] Blaming: store_jb.smx
L 08/06/2022 - 19:30:50: [SM] Call stack trace:
L 08/06/2022 - 19:30:50: [SM]   [0] SetFailState
L 08/06/2022 - 19:30:50: [SM]   [1] Line 3824, addons/sourcemod/scripting/store.sp::SQL_LoadParents
L 08/06/2022 - 19:30:51: [weapons.smx] SQLite DB connection successful
L 08/06/2022 - 19:30:51: [SM] Exception reported: Invalid data pack position, 8 is out of bounds (2)
L 08/06/2022 - 19:30:51: [SM] Blaming: smac_eac_banlist.smx
L 08/06/2022 - 19:30:51: [SM] Call stack trace:
L 08/06/2022 - 19:30:51: [SM]   [0] SetPackPosition
L 08/06/2022 - 19:30:51: [SM]   [1] Line 129, smac_eac_banlist.sp::OnSocketConnected
L 08/06/2022 - 19:30:51: [SM] Exception reported: Invalid data pack position, 8 is out of bounds (2)
L 08/06/2022 - 19:30:51: [SM] Blaming: smac_kac_banlist.smx
L 08/06/2022 - 19:30:51: [SM] Call stack trace:
L 08/06/2022 - 19:30:51: [SM]   [0] SetPackPosition
L 08/06/2022 - 19:30:51: [SM]   [1] Line 123, smac_kac_banlist.sp::OnSocketConnected
L 08/06/2022 - 19:30:51: [weapons.smx] Inactive players' data has been deleted
Forcing client reconnect (3)
L 08/06/2022 - 19:30:52: [SM] Exception reported: Invalid data pack position, 8 is out of bounds (2)
L 08/06/2022 - 19:30:52: [SM] Blaming: smac_kac_banlist.smx
L 08/06/2022 - 19:30:52: [SM] Call stack trace:
L 08/06/2022 - 19:30:52: [SM]   [0] SetPackPosition
L 08/06/2022 - 19:30:52: [SM]   [1] Line 123, smac_kac_banlist.sp::OnSocketConnected
L 08/06/2022 - 19:30:52: [SM] Exception reported: Invalid data pack position, 8 is out of bounds (2)
L 08/06/2022 - 19:30:52: [SM] Blaming: smac_eac_banlist.smx
L 08/06/2022 - 19:30:52: [SM] Call stack trace:
L 08/06/2022 - 19:30:52: [SM]   [0] SetPackPosition
L 08/06/2022 - 19:30:52: [SM]   [1] Line 129, smac_eac_banlist.sp::OnSocketConnected

**Comment by nuclearsilo583** [comment]
this store.smx is not from my github. You must be installed a different type of store plugin.
Also other plugin is error for some reason. Grab the latest version from the author.

**Comment by WizardJailbreak** [comment]
> this store.smx is not from my github. You must be installed a different type of store plugin. Also other plugin is error for some reason. Grab the latest version from the author.

Now im downloaded the your plugin, and still not working.
Console: 
weapon_max_before_cleanup - 0
weapon_recoil_scale - 2.0
weapon_reticle_knife_show - 1
weapon_sound_falloff_multiplier - 1.0
sv_camera_fly_enabled - missing cvar specified in bspconvar_whitelist.txt
Executing dedicated server config file
[PlayerSkin] Configs has executed.
L 08/06/2022 - 21:22:56: [mapchooser_extended.smx] Loaded map list for csgo.
Unknown command "sv_tag"
Writing cfg/banned_user.cfg.
Writing cfg/banned_ip.cfg.
Unknown command "sv_maxcmdrate"
--------------------------------------------------------
sv_pure value unchanged (current value is 0).
--------------------------------------------------------
exec: couldn't exec gamemode_casual_server.cfg
CHostage::Precache: missing hostage models for map jb_summer_jail_v3. Adding the default models.
Attempted to create unknown entity type weapon_m4a1_silencer!
func_physbox (soccerball_phys) at (-620.990 -1632.790 -143.000) using obsolete or unknown material type.
Commentary: Could not find commentary data file 'maps/jb_summer_jail_v3_commentary.txt'. 
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
[PlayerSkin] Table has created if not existed.
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file addons/sourcemod/configs/admin_skin.ini
Admin_Skins, (*def*), 
[-N- Arms Fix] Nothing changed, config is ready.
[AbNeR RES] SOUNDS: 10 sounds loaded from "sound/misc/tecnohard"
Unknown command "weapons"
L 08/06/2022 - 21:22:57: [store_jb.smx] Init CP...
L 08/06/2022 - 21:22:57: [sm_ctban.smx] Default database database connection failure: [2002]: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
L 08/06/2022 - 21:22:57: [SM] Exception reported: Error while connecting to default database. Exiting.
L 08/06/2022 - 21:22:57: [SM] Blaming: sm_ctban.smx
L 08/06/2022 - 21:22:57: [SM] Call stack trace:
L 08/06/2022 - 21:22:57: [SM]   [0] SetFailState
L 08/06/2022 - 21:22:57: [SM]   [1] Line 1638, D:\Perso\expbox\addons\sourcemod\scripting\sm_ctban.sp::DB_Callback_Connect
L 08/06/2022 - 21:22:58: [SM] Exception reported: Can not retrieve item.parent from database: no result row
L 08/06/2022 - 21:22:58: [SM] Blaming: store_jb.smx
L 08/06/2022 - 21:22:58: [SM] Call stack trace:
L 08/06/2022 - 21:22:58: [SM]   [0] SetFailState
L 08/06/2022 - 21:22:58: [SM]   [1] Line 3824, addons/sourcemod/scripting/store.sp::SQL_LoadParents
L 08/06/2022 - 21:22:58: [weapons.smx] SQLite DB connection successful
L 08/06/2022 - 21:22:58: [weapons.smx] Inactive players' data has been deleted
L 08/06/2022 - 21:22:58: [SM] Exception reported: Invalid data pack position, 8 is out of bounds (2)
L 08/06/2022 - 21:22:58: [SM] Blaming: smac_eac_banlist.smx
L 08/06/2022 - 21:22:58: [SM] Call stack trace:
L 08/06/2022 - 21:22:58: [SM]   [0] SetPackPosition
L 08/06/2022 - 21:22:58: [SM]   [1] Line 129, smac_eac_banlist.sp::OnSocketConnected
L 08/06/2022 - 21:22:58: [SM] Exception reported: Invalid data pack position, 8 is out of bounds (2)
L 08/06/2022 - 21:22:58: [SM] Blaming: smac_kac_banlist.smx
L 08/06/2022 - 21:22:58: [SM] Call stack trace:
L 08/06/2022 - 21:22:58: [SM]   [0] SetPackPosition
L 08/06/2022 - 21:22:58: [SM]   [1] Line 123, smac_kac_banlist.sp::OnSocketConnected
Forcing client reconnect (3)
L 08/06/2022 - 21:23:00: [SM] Exception reported: Invalid data pack position, 8 is out of bounds (2)
L 08/06/2022 - 21:23:00: [SM] Blaming: smac_eac_banlist.smx
L 08/06/2022 - 21:23:00: [SM] Call stack trace:
L 08/06/2022 - 21:23:00: [SM]   [0] SetPackPosition
L 08/06/2022 - 21:23:00: [SM]   [1] Line 129, smac_eac_banlist.sp::OnSocketConnected
L 08/06/2022 - 21:23:00: [SM] Exception reported: Invalid data pack position, 8 is out of bounds (2)
L 08/06/2022 - 21:23:00: [SM] Blaming: smac_kac_banlist.smx
L 08/06/2022 - 21:23:00: [SM] Call stack trace:
L 08/06/2022 - 21:23:00: [SM]   [0] SetPackPosition
L 08/06/2022 - 21:23:00: [SM]   [1] Line 123, smac_kac_banlist.sp::OnSocketConnected

**Comment by nuclearsilo583** [comment]
Lị what I have commented. The current store plugin you're running is not plugin from my github. You must installed a different modified store by someone.
Please delete the store.smx and download this repo and compile.

**Comment by azalty** [comment]
It's the CTBan plugin from databomb, however, it supports MySQL so my guess is that they didn't set up their databases.cfg correctly
