### ISSUE TITLE
Inquiries and suggestions for plugins

### ISSUE THREAD

**Issue by INewWorldI** [nuclearsilo583/zephyrus-store-preview-new-syntax#98]
1. For gambling plugins, the larger the credit, the greater the amount of credit you can get. I wish there was a cfg that could control this.

2. In the case of !daily, players can do it again 24 hours after typing the command. I would like this to be initialized from 3 am or 4 am based on standard time. It may be inefficient, but this is the method used by various game companies to reset daily tasks.

3. As for the player skin, if I select Terror when I use a skin that can only use CT, there is a problem that the unpurchased skin is automatically installed when Terror. Can I have this only be equipped with the default skin or purchased skins?

4. I don't know if it's a bug, but sometimes, if you use a custom weapon, especially the knife, the default weapon is loaded. In this case, swap to another weapon and it will return to normal. This problem often occurs in prisons or mini-game servers.

**Comment by azalty** [comment]
> In the case of !daily, players can do it again 24 hours after typing the command. I would like this to be initialized from 3 am or 4 am based on standard time. It may be inefficient, but this is the method used by various game companies to reset daily tasks.

Great suggestion!

**Comment by INewWorldI** [comment]
> > In the case of !daily, players can do it again 24 hours after typing the command. I would like this to be initialized from 3 am or 4 am based on standard time. It may be inefficient, but this is the method used by various game companies to reset daily tasks.
> 
> Great suggestion! Might work on it later, it can be done easily with [FormatTime()](https://sourcemod.dev/#/sourcemod/function.FormatTime)

That's a good answer, I'm looking forward to it

And additionally, there is a bug in the chat processor where purple is displayed as the team color. Please check. This is question 5

5. I know the purple color tag is recognized as a team chat, of course, there is already a color close to pink. But I know that purple can be used enough in csgo.
6. 
![컬러](https://user-images.githubusercontent.com/32818386/184059094-22c8b5df-392f-46c5-95ab-c53e94a75a17.png)

**Comment by nuclearsilo583** [comment]
Sorry for late response since I dont have much time.
1. So you say if you bet the max credits allowed in betting you will get about 50% of bonuses.
2. Yes, I have thought about this feature before and started to update instead of 24 hours waiting since it isnt efficient.
3. I quite dont understand your point. Could you explain more.
4. Due to csgo's client's prediction in prediected_viewmodel which always show the default model first and csgo'd problem. This problem could appear sometime.

**Comment by INewWorldI** [comment]
Oh okay ... and there seems to be a bug. The latest patch raises the error 017: undefined symbol "g_cvarChatTag" bug.

**Comment by INewWorldI** [comment]
> Sorry for late response since I dont have much time.
> 
> 1. So you say if you bet the max credits allowed in betting you will get about 50% of bonuses.
> 2. Yes, I have thought about this feature before and started to update instead of 24 hours waiting since it isnt efficient.
> 3. I quite dont understand your point. Could you explain more.
> 4. Due to csgo's client's prediction in predicted_viewmodel which always show the default model first and csgo'd problem. This problem could appear sometime.
> 5. You can't use purple color of spectator team of csgo.

3 >> If only I was using the counter-terror skin. So I don't know if I can use all or the Terror skin at the same time when I choose Terror Team, but if not, the base model should come out. However, it seemed that a skin that I did not purchase at random came out.

**Comment by nuclearsilo583** [comment]
For playerskin you can both equip the ct and ts skin at the same time which were specified by team 2 or 3 (4 is using both team and this skin will be overrided). Sorry that I dont quite understand what you're talking about.

**Comment by INewWorldI** [comment]
No, I solved it.
In the past, when I went to TR wearing a CT skin, strangely at the time of testing, the model randomly wore a different skin than the one I had purchased or equipped.

As a result of asking the testers this time, it was confirmed that the default terrorist model appeared normally.

And I am very grateful that some of my suggestions have been reflected. thank you!
