### ISSUE TITLE
1/ - player:  UTIL_SetModel:  not precached

### ISSUE THREAD

**Issue by WizardJailbreak** [nuclearsilo583/zephyrus-store-preview-new-syntax#99]
Hi
When i connect to my server, the server is write this:

1/ - player:  UTIL_SetModel:  not precached: models/player/custom_player/kuristaja/banana_joe/banana_joe.mdl
1/ - player:  UTIL_SetModel:  not precached: models/player/custom_player/kuristaja/banana_joe/banana_joe.mdl

1/ - player:  UTIL_SetModel:  not precached: models/player/custom_player/kuristaja/banana_joe/banana_joe.mdl

And the server is crashing

**Comment by INewWorldI** [comment]
Please use the download/precache plugin used in sourcemod.

**Comment by nuclearsilo583** [comment]
The problem was solved through PM.
